Added Window.PreCloseListener that can be used to prevent window close
vaadin/framework pull request #10535
Opened 2018-01-14 06:53 UTC by jreznot

Window.PreCloseListener is triggered only if users try to close window
from client side. If PreCloseListener sets preventClose flag into event
object then window close is not performed.

2018-01-14 12:02 UTC, jreznot commented
Usually, this event is needed when we want to show "Unsaved changes" dialog to users and prevent window close.

2018-01-26 10:29 UTC, jreznot commented
It would be great to see this changes in the upcoming 8.4 release

2018-02-13 08:46 UTC, elmot commented
The idea on the change is pretty good, but I prefer to have it more in line with existing API. Please have a look at 
`ViewChangeListener.beforeViewChange()` and rewrite the code similar way.

---

Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5D8ueP06KOLZvfdX9G:-L5D8ueP06KOLZvfdX9H:bo0yr0j) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L46)):*
> ```Java
> import java.io.Serializable;
> import java.lang.reflect.Method;
> import java.util.*;
> ```

Please expand to individual imports. We do not use asterisk imports in Framework. 

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 243 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5D9XdhCejMDASzfA7P:-L5D9XdhCejMDASzfA7Q:bsg1xnj) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L243)):*
> ```Java
>     }
> 
>     protected void closeFromClient() {
> ```

Missing javadoc and empty `@since`. They are mandatory for protected and public classes and members

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 744 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5D9KkvO80JybB6TBYG:-L5D9KkvO80JybB6TBYH:b-9ohhlq) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L744)):*
> ```Java
>      * {@link UI#removeWindow(Window)} call.
>      *
>      * @since 8.3
> ```

`@since` should be empty. they are set to a particular version when released.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 786 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5DCKGggZBRE7XnQ6kn:-L5DCKGhmiP1tB4mOUac:b-plvhmi) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L786)):*
> ```Java
>      * </p>
>      *
>      * @since 8.3
> ```

`@since` should be empty.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 810 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5DCPY6A_clD0ZXgQVD:-L5DCPY6A_clD0ZXgQVE:bgg0769) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L810)):*
> ```Java
>      *
>      * @param listener
>      *            the PreCloseListener to add, not null
> ```

According to our code conventions, the class should be `WindowBeforeCloseListener`. And the same for the event, all the methods etc.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 811 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5DC_ME7fvXX1obA2F8:-L5DC_ME7fvXX1obA2F9:b-plvhmi) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L811)):*
> ```Java
>      * @param listener
>      *            the PreCloseListener to add, not null
>      * @since 8.3
> ```

`@since` should be empty.

---

*[server/src/test/java/com/vaadin/tests/server/components/WindowTest.java, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5DCeZBkEGWX6D5JfJs:-L5DCeZBkEGWX6D5JfJt:bf1fu0w) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/test/java/com/vaadin/tests/server/components/WindowTest.java#L6)):*
> ```Java
> import java.util.Map;
> 
> import com.vaadin.ui.Window.*;
> ```

We do not use asterisk imports. For tests the rule isn't that strict but anyway.

---

*[uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5DKwaeBoyl66xye8Sx:-L5DKwaeBoyl66xye8Sy:b-pw8s8c) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java#L13)):*
> ```Java
> import static org.junit.Assert.assertTrue;
> 
> public class WindowPreCloseListenerTest extends MultiBrowserTest {
> ```

SingleBrowserTest is enough, I think

---

*[uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5DD0lVFvLoQ4il-pm4:-L5DD0lVFvLoQ4il-pm5:be1v4wn) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java#L15)):*
> ```Java
> public class WindowPreCloseListenerTest extends MultiBrowserTest {
> 
>     @Override
> ```

Please add `@Before` in sake of readability

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10535#-:-L5DK5vGAjSPuSd1jgNS:b-p7n7ut)*
<!-- Sent from Reviewable.io -->

2018-02-19 18:58 UTC, jreznot commented
I've redesigned API and tried to fix all the review comments

2018-02-21 09:23 UTC, elmot commented
Reviewed 4 of 7 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 271 at r4](https://reviewable.io:443/reviews/vaadin/framework/10535#-L5lHrb-54cxxAuNTbxt:-L5lHrb-54cxxAuNTbxu:b-4a2wjf) ([raw file](https://github.com/vaadin/framework/blob/66f3a2a4097a89afe91b88a360a03cf77d4e230b/server/src/main/java/com/vaadin/ui/Window.java#L271)):*
> ```Java
>      * @return true if the window close should be allowed, false to silently
>      *         block the close operation
>      */
> ```

missing `@since`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10535)*
<!-- Sent from Reviewable.io -->

2018-03-27 20:07 UTC, jreznot commented
Reviewed 4 of 9 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 271 at r4](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5lHrb-54cxxAuNTbxt:-L8d3H3o0CfppBNmwI7n:bs7wumb) ([raw file](https://github.com/vaadin/framework/blob/66f3a2a4097a89afe91b88a360a03cf77d4e230b/server/src/main/java/com/vaadin/ui/Window.java#L271)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing `@since`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10535)*
<!-- Sent from Reviewable.io -->

2018-03-27 20:07 UTC, jreznot commented
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 243 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5D9XdhCejMDASzfA7P:-L8d3_sbDDyB7gqpO2Bv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L243)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Missing javadoc and empty `@since`. They are mandatory for protected and public classes and members
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 744 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5D9KkvO80JybB6TBYG:-L8d3aeS99iNBiXVfRCm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L744)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since` should be empty. they are set to a particular version when released.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 786 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5DCKGggZBRE7XnQ6kn:-L8d3bJEBZ_I3xINyvxh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L786)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since` should be empty.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 810 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5DCPY6A_clD0ZXgQVD:-L8d3bzU7zAzOCk2BQEo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L810)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

According to our code conventions, the class should be `WindowBeforeCloseListener`. And the same for the event, all the methods etc.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 811 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5DC_ME7fvXX1obA2F8:-L8d3cLx6dWsUh35lBFk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L811)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since` should be empty.
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/components/WindowTest.java, line 6 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5DCeZBkEGWX6D5JfJs:-L8d3dVh0EAAvQXUHCU7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/test/java/com/vaadin/tests/server/components/WindowTest.java#L6)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

We do not use asterisk imports. For tests the rule isn't that strict but anyway.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java, line 13 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5DKwaeBoyl66xye8Sx:-L8d3fhj1OPRAQvVJrB1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java#L13)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

SingleBrowserTest is enough, I think
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java, line 15 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5DD0lVFvLoQ4il-pm4:-L8d3ezQ9DSlYG3AAT-x:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/uitest/src/test/java/com/vaadin/tests/components/window/WindowPreCloseListenerTest.java#L15)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please add `@Before` in sake of readability
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10535)*
<!-- Sent from Reviewable.io -->

2018-03-27 20:07 UTC, jreznot commented
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 46 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10535#-L5D8ueP06KOLZvfdX9G:-L8d3he870-I8Gt0N5gr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efe2ccb1db892dc64db1bed52401af10ed3a8878/server/src/main/java/com/vaadin/ui/Window.java#L46)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please expand to individual imports. We do not use asterisk imports in Framework. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10535)*
<!-- Sent from Reviewable.io -->

2018-03-27 20:09 UTC, jreznot commented
I totally missed where to fix review points (
Just marked all the points as Done.

2018-05-08 17:08 UTC, jreznot commented
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 271 at r4](https://reviewable.io/reviews/vaadin/framework/10535#-L5lHrb-54cxxAuNTbxt:-LC-iQ8HDqk8jaxg34V_:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/66f3a2a4097a89afe91b88a360a03cf77d4e230b/server/src/main/java/com/vaadin/ui/Window.java#L271)):*
<details><summary><i>Previously, jreznot (Yuriy Artamonov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10535)*
<!-- Sent from Reviewable.io -->

2018-05-08 17:10 UTC, jreznot commented
LGTM

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10535#-:-LC-ixYP-37v3G6QZrdk:bb6ywmx)*
<!-- Sent from Reviewable.io -->

2018-09-06 11:22 UTC, mehdi-vaadin requested changes
Please format your code. It can be done by this command `mvn process-sources`. Also, a test should be added for the case a confirm dialog is shown before closing the windows for the user to make their decision. After all, the purpose of this PR is to show the user a message for unsaved changes.

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10535#-:-LLhrg3V24EQsB9KSlHu:b-7o89vm)* status: all files reviewed, 18 unresolved discussions (waiting on @elmot and @jreznot)

___
*[server/src/main/java/com/vaadin/ui/Window.java, line 116 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiKjWU4Ahkjm2nXpOI:-LLiKjWU4Ahkjm2nXpOJ:b-hwl0zd) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L116)):*
> ```
> private LinkedHashSet<WindowBeforeCloseListener> beforeCloseListeners = null;
> ```
This is not needed and it's better to use `addListener` from `AbstractComponent` like one of the previous comments. I can't see why it has been changed. So, it should be removed and the related code should be changed accordingly.
___
*[server/src/main/java/com/vaadin/ui/Window.java, line 257 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiOgRJAqH1bi8rtcL1:-LLiOgRJAqH1bi8rtcL2:bk6jipr) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L257)):*
> ```
>      * Fires an event before window close.
>      * <p>
> ```
This comment is not necessary and should be removed.  Actually, it's deducted from the method name.
___
*[server/src/main/java/com/vaadin/ui/Window.java, line 268 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiR6U12VjEjaBTx28C:-LLiR6U12VjEjaBTx28D:bvu10om) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L268)):*
> ```
> not null
> ```
So, we need a `Objects.requireNonNull` in the code. And, the rest of the comment about `event` is extra.
___
*[server/src/main/java/com/vaadin/ui/Window.java, line 275 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiRcog8k-YGjQiBML6:-LLiRcog8k-YGjQiBML7:bmqjhpr) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L275)):*
> ```
>         // a copy of the listener list is needed to avoid
>         // ConcurrentModificationException as a listener can add/remove
>         // listeners
> ```
Since `beforeCloseListeners` should be removed, `getListeners` method should be called to get the list of listeners. So, no need to make a copy of the list.
___
*[server/src/main/java/com/vaadin/ui/Window.java, line 800 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiT1Qw1sL1j4hVaTtz:-LLiT1Qw1sL1j4hVaTu-:b3c2l2d) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L800)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         /**
>          * Gets the Window.
>          *
>          * @return the window.
>          */
> ```
</details>

Unnecessary comment.
___
*[server/src/main/java/com/vaadin/ui/Window.java, line 816 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiT_JY7tRMDxSZgUlb:-LLiT_JY7tRMDxSZgUlc:b32aabv) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L816)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>      * <p>
>      * Implementation of the listener may cancel window close using
>      * {@link WindowBeforeCloseEvent#setClosePrevented(boolean)} method call.
>      * </p>
>      *
>      * @since
> ```
</details>

Not relevant any more. Should be removed.
___
*[server/src/main/java/com/vaadin/ui/Window.java, line 858 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiVDE46q4-A8DSkP4A:-LLiVDE46q4-A8DSkP4B:bnzsv5n) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L858)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
>         if  (beforeCloseListeners == null) {
>             beforeCloseListeners = new LinkedHashSet<>();
>         }
>  
>         beforeCloseListeners.add(listener);
>  
>         return () -> {
>             if (beforeCloseListeners != null) {
>                 beforeCloseListeners.remove(listener);
>                 if (beforeCloseListeners.isEmpty()) {
>                     beforeCloseListeners = null;
>                 }
>             }
>         };
> ```
</details>

`addListener` method should be used instead.
___
*[server/src/main/java/com/vaadin/ui/Window.java, line 1686 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiVLdTAIOo4QYbzB49:-LLiVLdTAIOo4QYbzB4A:b737odl) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/server/src/main/java/com/vaadin/ui/Window.java#L1686)):*
<details><summary><i alt="summary">Quoted 23 lines of code…</i></summary>

> ```
>     @Override
>     public Collection<?> getListeners(Class<?> eventType) {
>         if (WindowBeforeCloseEvent.class.isAssignableFrom(eventType)) {
>             if (beforeCloseListeners == null) {
>                 return Collections.EMPTY_LIST;
>             } else {
>                 return Collections
>                         .unmodifiableCollection(beforeCloseListeners);
>             }
>         } else if (ConnectorEvent.class.isAssignableFrom(eventType)
>                 || Component.Event.class.isAssignableFrom(eventType)) {
>             if (beforeCloseListeners == null) {
>                 return super.getListeners(eventType);
>             } else {
>                 Set<Object> listeners = new LinkedHashSet<>();
>                 listeners.addAll(beforeCloseListeners);
>                 listeners.addAll(super.getListeners(eventType));
>                 return listeners;
>             }
>         }
>  
>         return super.getListeners(eventType);
>     }
> ```
</details>

should be removed.
___
*[uitest/src/main/java/com/vaadin/tests/components/window/WindowBeforeCloseListener.java, line 9 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiXKUe0YA5oqnsh1Dq:-LLiXKUe0YA5oqnsh1Dr:b-lk8svd) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/uitest/src/main/java/com/vaadin/tests/components/window/WindowBeforeCloseListener.java#L9)):*
> ```
> WindowBeforeCloseListener
> ```
Let's use a different name from the actual listener being tested here e.g. WindowWithBeforeCloseListener.
___
*[uitest/src/test/java/com/vaadin/tests/components/window/WindowBeforeCloseListenerTest.java, line 27 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLiZhGw8LmRURnKxxCt:-LLiZhGw8LmRURnKxxCu:bh78nzr) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/uitest/src/test/java/com/vaadin/tests/components/window/WindowBeforeCloseListenerTest.java#L27)):*
> ```
> "Unexpected log contents,"
> ```
A more clear message is needed here e.g. "Unexpected log contents, the CloseListener is not called."
___
*[uitest/src/test/java/com/vaadin/tests/components/window/WindowBeforeCloseListenerTest.java, line 28 at r5](https://reviewable.io/reviews/vaadin/framework/10535#-LLi_O1w4-G2tb515lN7:-LLi_O1w4-G2tb515lN8:b-4cj4ud) ([raw file](https://github.com/vaadin/framework/blob/4a42454a56b97122aa77976b2f3a54004c93d760/uitest/src/test/java/com/vaadin/tests/components/window/WindowBeforeCloseListenerTest.java#L28)):*
> ```Java
>         $(WindowElement.class).$(ButtonElement.class).first().click();
>         assertEquals("Unexpected log contents,",
>                 "1. Window 'Sub-window' closed", g [...]

2018-10-29 08:17 UTC, jreznot commented
It seems that there are no real need in the community for this feature except our case. Thanks for the comments, I'm closing this.

2018-10-29 08:17 UTC, closed without merging