Change documentation code samples to produce expected output
vaadin/framework pull request #11093
Opened 2018-07-27 13:31 UTC by neno--

I used ```yearOfBirth``` field name used in Vaadin 8 documentation sample, which fits more nicely than ```age```.
Also, when trying to create property from said field, wrong ```born``` field name is used.

2018-07-27 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/framework?pullRequest=11093) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/framework?pullRequest=11093) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/framework?pullRequest=11093) it.</sub>

2018-08-09 07:13 UTC, anasmi commented
___
*[documentation/datamodel/datamodel-items.asciidoc, line 79 at r1](https://reviewable.io/reviews/vaadin/framework/11093#-LJSWCy32cih12rJWH6P:-LJSWCy32cih12rJWH6Q:b-16gego) ([raw file](https://github.com/vaadin/framework/blob/3fbf6dc9041261e04579312028aab93134921495/documentation/datamodel/datamodel-items.asciidoc#L79)):*
> ```AsciiDoc
>     int    yearOfBirth;
> 
>     // Constructors omitted
> ```

Hi! And, first of all, thank you for contribution! : )
Could you add the constructor for the class? `public Person(String name, int yearOfBirth)`
Currently,  the example code below doesn't compile due to the missing constructor. 


<!-- Sent from Reviewable.io -->

2018-08-09 07:14 UTC, anasmi commented
___
*[documentation/datamodel/datamodel-items.asciidoc, line 93 at r1](https://reviewable.io/reviews/vaadin/framework/11093#-LJSXN767HCWFf_N99C3:-LJSXN767HCWFf_N99C4:bvb23jq) ([raw file](https://github.com/vaadin/framework/blob/3fbf6dc9041261e04579312028aab93134921495/documentation/datamodel/datamodel-items.asciidoc#L93)):*
> ```AsciiDoc
>     }
>     
>     public void setYearOfBirth(Integer yearOfBirth) {
> ```

The same here


<!-- Sent from Reviewable.io -->

2018-08-09 07:15 UTC, anasmi requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11093)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @neno--)

___
*[documentation/datamodel/datamodel-items.asciidoc, line 77 at r1](https://reviewable.io/reviews/vaadin/framework/11093#-LJSXXujDBrS9mH5xroS:-LJSXXukBEUG12CgI_e0:bwzknt6) ([raw file](https://github.com/vaadin/framework/blob/3fbf6dc9041261e04579312028aab93134921495/documentation/datamodel/datamodel-items.asciidoc#L77)):*
> ```AsciiDoc
> public class Person {
>     String name;
>     int    yearOfBirth;
> ```

It looks like you have redundant spaces here. Could you remove those? 
___
*[documentation/datamodel/datamodel-items.asciidoc, line 89 at r1](https://reviewable.io/reviews/vaadin/framework/11093#-LJSX81i3iLlaUJzNVV0:-LJSX81i3iLlaUJzNVV1:b-m27o8c) ([raw file](https://github.com/vaadin/framework/blob/3fbf6dc9041261e04579312028aab93134921495/documentation/datamodel/datamodel-items.asciidoc#L89)):*
> ```AsciiDoc
>     }
>     
>     public Integer getYearOfBirth() {
> ```

Also, this is "picky" comment, but could you change the `Integer` to `int`? There is no need for autoboxing. 


<!-- Sent from Reviewable.io -->

2018-08-09 08:30 UTC, neno-- commented
I pushed the requested changes.

2018-08-09 08:57 UTC, anasmi approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11093)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-09 10:00 UTC, elmot approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11093#-:-LJT7J10-bB2aicz9CUD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-09 10:01 UTC, merged