Add fallback resolvers for CurrentInstance (#10974)
vaadin/framework pull request #11145
Opened 2018-08-29 10:43 UTC by gilberto-torrezan

This allow applications to inject custom default instances when the
current instances cannot be found by regular means.

For example, when VaadinServlet.getCurrent() would return null, a
fallback resolver could be invoked to properly create the servlet and
return it.

Fix #10978

2018-08-29 11:07 UTC, elmot requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11145)* status: all files reviewed, 1 unresolved discussion (waiting on @gilberto-torrezan)

___
*[server/src/test/java/com/vaadin/util/CurrentInstanceTest.java, line 165 at r1](https://reviewable.io/reviews/vaadin/framework/11145#-LL4Lwrc6H6N9MXZbxX4:-LL4LwrdEAid2JRVtQ_r:b-hm9rik) ([raw file](https://github.com/vaadin/framework/blob/58be4c467099a8a9d729ac2873814e95728084d6/server/src/test/java/com/vaadin/util/CurrentInstanceTest.java#L165)):*
> ```Java
>         assertNull(VaadinSession.getCurrent());
>     }
>     
> ```

Extra spaces. Please run `mvn process-sources' or `mvn install`  before committing


<!-- Sent from Reviewable.io -->

2018-08-29 11:11 UTC, gilberto-torrezan reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11145)* status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

___
*[server/src/test/java/com/vaadin/util/CurrentInstanceTest.java, line 165 at r1](https://reviewable.io/reviews/vaadin/framework/11145#-LL4Lwrc6H6N9MXZbxX4:-LL4NHLn5Xm1gGqHBLvw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/58be4c467099a8a9d729ac2873814e95728084d6/server/src/test/java/com/vaadin/util/CurrentInstanceTest.java#L165)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Extra spaces. Please run `mvn process-sources' or `mvn install`  before committing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-29 11:31 UTC, elmot approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11145#-:-LL4Rz8YBea-HZrydL6V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-09-01 09:37 UTC, elmot commented
Please rebase on top of current master

2018-09-03 12:21 UTC, merged