Remove objects from ActiveDataHandler that are no longer available in used DataProvider
vaadin/framework pull request #11167
Opened 2018-09-05 13:12 UTC by elmot

Related to #10471
on behalf of @tomasblahut:

After calling _DataProvider#refreshAll()_, objects, that were previously kept as active by _DataCommunicator.ActiveDataHandler_ (hereafter refered to as "_ActiveDataHandler_"), but are no longer supplied by current _DataProvider_, are not dropped from _ActiveDataHandler_ and stay active. 

Consider a use case where _Grid_ is displaying data from a _ListDataProvider_ and some of its columns use _Components_ in order to render cells content. Then replacing contents of _ListDataProvider#backend_ collection (with objects, for which _DataProvider#getId(object)_ yields a different id than for those previous ones) and calling _DataProvider#refreshAll()_ afterwards results in increasing attached _Component_ count and client side rendering performance drop.

This change causes all active objects inside _ActiveDataHandler_ to be marked as dropped while _DataCommunicator_ is sending data to client with _reset_ field set to `true`. Existing logic for dropping active objects inside _ActiveDataHandler_ prevents objects, requested by client side after reset has occured, from being dropped, even if they are marked that way. Dropping "old no longer available" objects from _ActiveDataHandler_, enables _DataCommunicator_ to destroy them and detach any _Components_ created by e.g. _Grid.Column_ _ValueProviders_.

Bellow is a simple _UI_ describing a way in which this issue can be reproduced. Increasing _Component_ count (_Referenced paintables_ variable using debug window) can be observed with every press of a button.

```java
public class MyUI extends UI {

    private static final int GRID_ROW_COUNT = 20;
    
    private final List<GridRowPojo> gridRowObjects = new ArrayList<>();

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        refreshGridRowObjects();
        setContent(prepareLayout());
    }

    private void refreshGridRowObjects() {
        gridRowObjects.clear();

        for (int index = 0; index < GRID_ROW_COUNT; index++) {
            gridRowObjects.add(new GridRowPojo(UUID.randomUUID().toString()));
        }
    }

    private VerticalLayout prepareLayout() {
        Grid<GridRowPojo> grid = new Grid<>();
        grid.setSizeFull();
        grid.addColumn(source -> {
            TextField textField = new TextField();
            textField.setValue(source.getName());
            return textField;
        }, new ComponentRenderer());
        grid.setDataProvider(DataProvider.ofCollection(gridRowObjects));

        Button btnRefresh = new Button("Refresh [new objects]", event -> {
            refreshGridRowObjects();
            grid.getDataProvider().refreshAll();
        });

        HorizontalLayout layBtns = new HorizontalLayout(btnRefresh);

        VerticalLayout layout = new VerticalLayout(grid, layBtns);
        layout.setSizeFull();
        layout.setExpandRatio(grid, 1.0f);
        return layout;
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }

    public static class GridRowPojo {

        private final String name;

        public GridRowPojo(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }
}

2018-09-06 08:42 UTC, tsuoanttila requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11167)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @elmot, @tsuoanttila, and @mehdi-vaadin)

___
*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 145 at r1](https://reviewable.io/reviews/vaadin/framework/11167#-LLi0xquAdO--Z1TkVKI:-LLi0fX_9cwXSml0tH9h:b-6fejfp) ([raw file](https://github.com/vaadin/framework/blob/51c177322c277b1105d1aff83d9f9bd461d9ec1e/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L145)):*
> ```Java
>          * Marks all currently active data objects to be dropped.
>          */
>         public void dropAllActiveData() {
> ```

missing since
___
*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 170 at r1](https://reviewable.io/reviews/vaadin/framework/11167#-LLi0zBIDl3umtrVW7eO:-LLi0zBIDl3umtrVW7eP:b-6fejfp) ([raw file](https://github.com/vaadin/framework/blob/51c177322c277b1105d1aff83d9f9bd461d9ec1e/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L170)):*
> ```Java
>          *         {@code false} if not
>          */
>         public boolean isDropped(T dataObject) {
> ```

missing since


<!-- Sent from Reviewable.io -->

2018-09-06 08:42 UTC, tsuoanttila reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11167)* status: all files reviewed, 2 unresolved discussions (waiting on @elmot and @mehdi-vaadin)



<!-- Sent from Reviewable.io -->

2018-09-06 12:29 UTC, elmot reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11167)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @tsuoanttila and @mehdi-vaadin)

___
*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 145 at r1](https://reviewable.io/reviews/vaadin/framework/11167#-LLi0xquAdO--Z1TkVKI:-LLiqv0n7VZAYw_2YPtH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/51c177322c277b1105d1aff83d9f9bd461d9ec1e/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L145)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

missing since
</blockquote></details>

Done.
___
*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 170 at r1](https://reviewable.io/reviews/vaadin/framework/11167#-LLi0zBIDl3umtrVW7eO:-LLiqvLu5-7YTqsdez80:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/51c177322c277b1105d1aff83d9f9bd461d9ec1e/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L170)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

missing since
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-07 06:52 UTC, tsuoanttila approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mehdi-vaadin)



<!-- Sent from Reviewable.io -->

2018-09-07 07:19 UTC, merged