Increase max treegrid depth
vaadin/framework pull request #11375
Opened 2018-12-14 14:08 UTC by OlliTietavainenVaadin

Currently, rows deeper than 16 won't get indented. This fix updates the max depth to 32.

2018-12-17 08:14 UTC, ZheSun88 requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11375)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11375#-LTvCxVPBC8oT1DmGX_X:-LTvCxVPBC8oT1DmGX_Y:by7ksrn) (no related file):*
By checking the original ticket, I have two questions:
1. the ticket mentioned that tree doesn't expand correctly at depth 5, is this related to this max depth change?
2. by this fix, will the problem still exist for the items after 32? 

---


<!-- Sent from Reviewable.io -->

2018-12-17 08:17 UTC, OlliTietavainenVaadin reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11375)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11375#-LTvCxVPBC8oT1DmGX_X:-LTvEI7c98fCXhrN55pN:b-1noab8) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

By checking the original ticket, I have two questions:
1. the ticket mentioned that tree doesn't expand correctly at depth 5, is this related to this max depth change?
2. by this fix, will the problem still exist for the items after 32? 
</blockquote></details>

1. not related to this change
2. yes (but 32 levels should be enough for everybody)

---


<!-- Sent from Reviewable.io -->

2018-12-17 08:23 UTC, ZheSun88 requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11375)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11375#-LTvCxVPBC8oT1DmGX_X:-LTvFCF3CD9ZiID9CIKk:byelyrx) (no related file):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

1. not related to this change
2. yes (but 32 levels should be enough for everybody)
</blockquote></details>

1. should we create another ticket for this issue?
2. let us write a comment in the code and put the ticket number here also, so it would be easier for someone trying to fix it in the future.

---


<!-- Sent from Reviewable.io -->

2018-12-21 12:10 UTC, OlliTietavainenVaadin reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11375)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11375#-LTvCxVPBC8oT1DmGX_X:-LUFccFG3Bl8QOPivaW8:b4563v4) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

1. should we create another ticket for this issue?
2. let us write a comment in the code and put the ticket number here also, so it would be easier for someone trying to fix it in the future.
</blockquote></details>

1. https://github.com/vaadin/framework/issues/11391
2. Yes, I'll do some updates, but since I'll make a new PR for that since editing this PR in this repo is difficult.

---


<!-- Sent from Reviewable.io -->

2018-12-21 12:11 UTC, OlliTietavainenVaadin commented
Closing and making a new PR.

2018-12-21 12:11 UTC, closed without merging