WIP - Reset Combobox internal state
vaadin/framework pull request #11412
Opened 2019-01-08 13:45 UTC by ZheSun88

Thanks for submitting a pull request!
Please confirm that your pull request follows our guidelines found in CONTRIBUTING and that you provide enough information so that we can review your pull request.

<Description of pull request, e.g. "Fix Grid Column not sortable with backend data and sort property">

Fixes #<replace with an issue number>

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

2019-02-22 13:10 UTC, ZheSun88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 458 at r14](https://reviewable.io/reviews/vaadin/framework/11412#-LZKHPcj5vxiyu_vR8Hp:-LZKHPcj5vxiyu_vR8Hq:b-4v1lbr) ([raw file](https://github.com/vaadin/framework/blob/d56f2ff4e7dd5e54b738c878190834ddffd5ab8d/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L458)):*
> ```Java
>      */
>     private void clearNewItemHandling() {
>         pendingNewItemValue = null;
> ```

This checking has been removed as all the other places which use this method has its own checking before calling this method. one place has even a conflict condition see below
```
private void onSelectionChange() {
        ....
        if (isNewItemStillPending()
                && pendingNewItemValue == getState().selectedItemCaption) {
            // no automated selection handling required
            clearNewItemHandling();
        }
        ....
```
for this case it requires `isNewItemStillPending == true`. 


<!-- Sent from Reviewable.io -->

2019-03-01 13:34 UTC, pleku requested changes
> Reviewed 1 of 2 files at r14, 1 of 1 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1642 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMUQFAL4cyWkZZ0fI:-LZtMUQG6CLFKPM-eFiA:b-jz7ken) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1642)):*
> ```Java
>             // currentSuggestion should be set to match the value of the
>             // ComboBox, especially when a new item is added.
>             resetCurrentSuggestionIfNecessary(selectedKey, selectedCaption,
> ```

How is it known here that a new item has been added from the server ?

Answer by clarifying javadocs or comments in the code
___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1653 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMij2C3QP_pa5wGy1:-LZtMij2C3QP_pa5wGy2:b9rxckz) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1653)):*
> ```
>         private void resetCurrentSuggestionIfNecessary(String selectedKey,
>                 String selectedCaption, String selectedIconUri) {
> ```

This method name is not really that helpful as it makes one wonder:  _when is it necessary to reset the current suggestion ?_ 
___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 2130 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMzF2E3lzo1_olZ24:-LZtMzF2E3lzo1_olZ25:bu41ios) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L2130)):*
Why escape here already ? What is the meaning of the code when there is no selected key ?

The javadocs for this method say
>   * @param selectedKey
>     *            non-empty selected item key
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 134 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtS4zI0BsAdM1zedjs:-LZtS4zI0BsAdM1zedjt:b-2w6dwm) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L134)):*
> ```
> && pendingNewItemValue == getState().selectedItemCaption) 
> ```
I think this check should be replaced instead to use the `clearNewItemHandlingIfMatch(String value)` method with using the `getState().selectedItemCaption` as the value passed in..
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 191 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtNfxgDcVwpdIF0eFP:-LZtNfxgDcVwpdIF0eFQ:b-p7k53v) ([raw file](https://github.com/vaadin/framework/blob/6cc773fb7c717328fbce7255fa419581b7609a92/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L191)):*
> ```Java
>             // clear any previous handling as outdated
>             clearNewItemHandling();
>         }
> ```

Why is this removed ???

Is the `itemValue` then `null` or empty string when the user has pressed backspace to clear the input ?
Just wondering why the value is not sent to server every time it has changed from whatever was there previously
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 366 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtOY6IBEvljwDnZq24:-LZtOY6IBEvljwDnZq25:bxk0p6d) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L366)):*
> ```
>  getWidget().lastNewItemString = null;
> ```
Looks very scary to directly access fields in the widget... could this be behind a method instead ? I'm willing to allow new client side API for the widget 
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 196 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtSYZ0AJSyVaZYINC3:-LZtSYZ0AJSyVaZYINC4:b-rgxvm0) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/server/src/main/java/com/vaadin/ui/ComboBox.java#L196)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                     // let server side knows the new added item,
>                     // otherwise if the user trigger more events at the same
>                     // round with adding the new item, that will cause
>                     // issue https://github.com/vaadin/framework/issues/11343
> ```
</details>

Please reformulate in proper english


<!-- Sent from Reviewable.io -->

2019-03-06 14:24 UTC, ZheSun88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @pleku and @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1642 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMUQFAL4cyWkZZ0fI:-L_IEybQ2Mq_3rYn6G77:b-y68eg3) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1642)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

How is it known here that a new item has been added from the server ?

Answer by clarifying javadocs or comments in the code
</blockquote></details>

actually, this comment is kinda easy to make people misunderstand. For this reset, it is not necessary to emphasize the new item adding.

solution: Removed the ambiguous part from the comment.
___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1653 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMij2C3QP_pa5wGy1:-L_IFfqZ5Uo2aJIxvQRA:b-eguhv1) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1653)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>         private void resetCurrentSuggestionIfNecessary(String selectedKey,
>                 String selectedCaption, String selectedIconUri) {
> ```

This method name is not really that helpful as it makes one wonder:  _when is it necessary to reset the current suggestion ?_ 
</blockquote></details>

This method is resetting the current suggestion according to the corresponding conditions. 
As the condition is quite complicated to state in the method name, we can:
1) add comments for each condition;
2) add javadoc on the method.  
___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 2130 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMzF2E3lzo1_olZ24:-L_IErk33r2mKAV2d-m7:b-in6a2c) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L2130)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why escape here already ? What is the meaning of the code when there is no selected key ?

The javadocs for this method say
>   * @param selectedKey
>     *            non-empty selected item key
</blockquote></details>

Done. remove the return.
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 134 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtS4zI0BsAdM1zedjs:-L_IEqGUCqqHY-k5Wzd-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L134)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> && pendingNewItemValue == getState().selectedItemCaption) 
> ```
I think this check should be replaced instead to use the `clearNewItemHandlingIfMatch(String value)` method with using the `getState().selectedItemCaption` as the value passed in..
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 191 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtNfxgDcVwpdIF0eFP:-L_IIDXFBusaxzpnYZV3:b54i3yw) ([raw file](https://github.com/vaadin/framework/blob/6cc773fb7c717328fbce7255fa419581b7609a92/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L191)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why is this removed ???

Is the `itemValue` then `null` or empty string when the user has pressed backspace to clear the input ?
Just wondering why the value is not sent to server every time it has changed from whatever was there previously
</blockquote></details>

This was done in an experimental way: one case can fail the current logic is sending an empty string, which will result in duplicate on the added items. 
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 366 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtOY6IBEvljwDnZq24:-L_II0-pBu7nmRp6e9se:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L366)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>  getWidget().lastNewItemString = null;
> ```
Looks very scary to directly access fields in the widget... could this be behind a method instead ? I'm willing to allow new client side API for the widget 
</blockquote></details>

Done.
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 196 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtSYZ0AJSyVaZYINC3:-L_IHzbA11AZexnFnFRO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/server/src/main/java/com/vaadin/ui/ComboBox.java#L196)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                     // let server side knows the new added item,
>                     // otherwise if the user trigger more events at the same
>                     // round with adding the new item, that will cause
>                     // issue https://github.com/vaadin/framework/issues/11343
> ```
Please reformulate in proper english
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-07 07:24 UTC, pleku requested changes
> Reviewed 2 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1653 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMij2C3QP_pa5wGy1:-L_Lymlx2twSXqOKhpjy:bxjolxa) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1653)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

This method is resetting the current suggestion according to the corresponding conditions. 
As the condition is quite complicated to state in the method name, we can:
1) add comments for each condition;
2) add javadoc on the method.  
</blockquote></details>

You added comments that only repeat what the if-checks already state. This is not helpful in understanding when that method should be called.

The question that the method name or method level javadocs should answer is, _when is it necessary to reset current suggestion_.
An example answer could be:
```
/*
 * Updates the current suggestion based on values provided by the server.
 */
updateCurrentSuggestionBasedOnServerResponse(...)
``` 
This would elaborate on when/why it is necessary - the server has responded with the values and the suggestion is updated based on those.
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 191 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtNfxgDcVwpdIF0eFP:-L_M0brJ-9A55rsawLYJ:b653xlq) ([raw file](https://github.com/vaadin/framework/blob/6cc773fb7c717328fbce7255fa419581b7609a92/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L191)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

This was done in an experimental way: one case can fail the current logic is sending an empty string, which will result in duplicate on the added items. 
</blockquote></details>

Is there somewhere a check in the code for the empty string ? The parameter javadocs don't say anything about null or "".
At least now if there has been a previous suggestion of "f" and the next suggestion would be "", then this code would still run as the suggestion is not null and doesn't match the previous suggestion.

So either check for the empty string if it is necessary, or make it clear in the parameter javadocs what type of values this expects (null ? empty string?)
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 366 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtOY6IBEvljwDnZq24:-L_M-_llDcTfUukvW0Yv:b-f26b22) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L366)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You've misunderstood - wrapping this inside a method in this class doesn't help at all.
The new method should be in the `VComboBox` widget instead of touching its field properties from another class. You cannot hide the field by switching it to be private, but at least the code is a little better than before.
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 196 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtSYZ0AJSyVaZYINC3:-L_M1VPa3LtkNfqWzNvN:b-8nyi3w) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/server/src/main/java/com/vaadin/ui/ComboBox.java#L196)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done


<!-- Sent from Reviewable.io -->

2019-03-08 13:34 UTC, ZheSun88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @pleku and @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1653 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtMij2C3QP_pa5wGy1:-L_M4CSb9IMNMHzl633L:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1653)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You added comments that only repeat what the if-checks already state. This is not helpful in understanding when that method should be called.

The question that the method name or method level javadocs should answer is, _when is it necessary to reset current suggestion_.
An example answer could be:
```
/*
 * Updates the current suggestion based on values provided by the server.
 */
updateCurrentSuggestionBasedOnServerResponse(...)
``` 
This would elaborate on when/why it is necessary - the server has responded with the values and the suggestion is updated based on those.
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 191 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtNfxgDcVwpdIF0eFP:-L_SVV_96eI3j6JWUH_P:b-ienc03) ([raw file](https://github.com/vaadin/framework/blob/6cc773fb7c717328fbce7255fa419581b7609a92/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L191)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Is there somewhere a check in the code for the empty string ? The parameter javadocs don't say anything about null or "".
At least now if there has been a previous suggestion of "f" and the next suggestion would be "", then this code would still run as the suggestion is not null and doesn't match the previous suggestion.

So either check for the empty string if it is necessary, or make it clear in the parameter javadocs what type of values this expects (null ? empty string?)
</blockquote></details>

Added empty string checking.
___
*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 366 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtOY6IBEvljwDnZq24:-L_SVbnG8I8J4rht0jaq:bh0g9u4) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L366)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You've misunderstood - wrapping this inside a method in this class doesn't help at all.
The new method should be in the `VComboBox` widget instead of touching its field properties from another class. You cannot hide the field by switching it to be private, but at least the code is a little better than before.
</blockquote></details>

moved the method to VComboBox
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 196 at r17](https://reviewable.io/reviews/vaadin/framework/11412#-LZtSYZ0AJSyVaZYINC3:-L_SVgfj3_k7dJ5GWFzv:bb7f2mf) ([raw file](https://github.com/vaadin/framework/blob/968ee994c285f50f39849f7141752c6a30302209/server/src/main/java/com/vaadin/ui/ComboBox.java#L196)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2019-03-11 08:48 UTC, pleku requested changes
> Reviewed 1 of 4 files at r6, 1 of 2 files at r9, 1 of 3 files at r18, 3 of 3 files at r19.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: all files reviewed, 5 unresolved discussions (waiting on @ZheSun88)

___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 197 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fu0q4Ej850zenPbYx:-L_fu0q4Ej850zenPbYy:b-f26xyk) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/server/src/main/java/com/vaadin/ui/ComboBox.java#L197)):*
> ```
>                     // client side hanging. This is needed for cases that user fires
>                     // multi events (like adding and deleting) on a new item in
>                     // the same round trip.
> ```
Again, this is a bit hard to understand... I think you mean

>user fires

_user interaction fires_

> in the same round trip.

Either _during the same round trip_ OR _before the round trip_ ? 
___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemSize.java, line 17 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fv6NsCaXHgFud-vSh:-L_fv6NsCaXHgFud-vSi:b-ci3h6n) ([raw file](https://github.com/vaadin/framework/blob/41ef058ba8a99d7603e98e122b9e60fa2dbf33c9/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemSize.java#L17)):*
> ```Java
> import com.vaadin.ui.Label;
> 
> @Widgetset(TestingWidgetSet.NAME)
> ```

Is this removal somehow related ?
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 15 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fvDcRAE7C1a8_uhRa:-L_fvDcRAE7C1a8_uhRb:b-yy5xaz) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L15)):*
> ```
> @Ignore("Tests are not stable at all, locally pass")
> ```
Why _oh why_ do these not pass in CI but pass locally ?
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 16 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fvLPf4TWA9YlHQHlb:-L_fvLPf4TWA9YlHQHlc:bsudbrz) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L16)):*
> ```Java
> 
> @Ignore("Tests are not stable at all, locally pass")
> public class ComboBoxAddNewItemAndResetProviderAtSameRoundTest
> ```

Missing the issue # so that it is easier to get the context of the tests
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 104 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fvqYM-3veLCD3e6ln:-L_fvqYM-3veLCD3e6lo:bi2r4vr) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L104)):*
> ```
>                 new Actions(getDriver()).moveToElement(comboBoxElement, 10, 10)
>                         .moveByOffset(comboBoxElement.getSize().getWidth(), 0)
>                         .click().perform();
> ```
This looks quite fragile. How about adding a floating click target element somewhere in the UI that will not be close to the combo box or its dropdown ? E.g. a button


<!-- Sent from Reviewable.io -->

2019-03-11 10:57 UTC, ZheSun88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @pleku)

___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 197 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fu0q4Ej850zenPbYx:-L_gNvrKDGOr5_3iY0QB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/server/src/main/java/com/vaadin/ui/ComboBox.java#L197)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                     // client side hanging. This is needed for cases that user fires
>                     // multi events (like adding and deleting) on a new item in
>                     // the same round trip.
> ```
Again, this is a bit hard to understand... I think you mean

>user fires

_user interaction fires_

> in the same round trip.

Either _during the same round trip_ OR _before the round trip_ ? 
</blockquote></details>

Done.
___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemSize.java, line 17 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fv6NsCaXHgFud-vSh:-L_g-4r08hGRiDgIjcli:b4cohwa) ([raw file](https://github.com/vaadin/framework/blob/41ef058ba8a99d7603e98e122b9e60fa2dbf33c9/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemSize.java#L17)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Is this removal somehow related ?
</blockquote></details>

No this is not related to this change at all. It was used for running the super-dev-mode.
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 15 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fvDcRAE7C1a8_uhRa:-L_g-GcjCwTkuTlYYeF5:b-eqbll3) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L15)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> @Ignore("Tests are not stable at all, locally pass")
> ```
Why _oh why_ do these not pass in CI but pass locally ?
</blockquote></details>

That is a really really good question, but it is a mystery for me also. with CI, it fails randomly on the tests. 
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 16 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fvLPf4TWA9YlHQHlb:-L_g0cPe3HBJl0jcNqTN:b-digno5) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L16)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Missing the issue # so that it is easier to get the context of the tests
</blockquote></details>

Added issue number in the UI class
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 104 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fvqYM-3veLCD3e6ln:-L_gNy7DE0osPJ14ZitK:bb7f2mf) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L104)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 new Actions(getDriver()).moveToElement(comboBoxElement, 10, 10)
>                         .moveByOffset(comboBoxElement.getSize().getWidth(), 0)
>                         .click().perform();
> ```
This looks quite fragile. How about adding a floating click target element somewhere in the UI that will not be close to the combo box or its dropdown ? E.g. a button
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2019-03-18 14:05 UTC, pleku requested changes
> Reviewed 2 of 3 files at r20.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @pleku and @ZheSun88)

___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemSize.java, line 17 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fv6NsCaXHgFud-vSh:-LaG5oVhESmWwy2NM3is:bskglta) ([raw file](https://github.com/vaadin/framework/blob/41ef058ba8a99d7603e98e122b9e60fa2dbf33c9/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemSize.java#L17)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

No this is not related to this change at all. It was used for running the super-dev-mode.
</blockquote></details>

If it not related to this change at all, why is it part of this change then ? Meaning that probably there should not be any changes for this file then
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 15 at r19](https://reviewable.io/reviews/vaadin/framework/11412#-L_fvDcRAE7C1a8_uhRa:-LaG6JvQ3jut2po8HXjB:b-vzo1kz) ([raw file](https://github.com/vaadin/framework/blob/80acfc4244287ef7a96ac5a712d6806465c163a1/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L15)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

That is a really really good question, but it is a mystery for me also. with CI, it fails randomly on the tests. 
</blockquote></details>

What fails any how it fails ?

There is no information here why this test fails on CI or on what step it fails.

Adding an ignored test is pretty much the same as not testing at all. At minimal there should be a good reason for why the test fails and why it is OK to ignore it, instead of just silently failing


<!-- Sent from Reviewable.io -->

2019-04-09 13:28 UTC, pleku approved these changes
> Reviewed 1 of 1 files at r23, 1 of 1 files at r24.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-17 05:16 UTC, anasmi commented
Regarding the #10915 I am not able to reproduce it now in the Sampler (Also, there was this fix https://github.com/vaadin/framework/pull/11436 which might potentially interfere). Did you check the current master if the issue is persist there?  Also, there is no test for this issue

2019-04-17 05:32 UTC, anasmi requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @pleku and @ZheSun88)

___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRound.java, line 80 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-Lcdidjh-3ksMtIpMaa0:-Lcdidjh-3ksMtIpMaa1:bbdtesn) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRound.java#L80)):*
> ```Java
>     }
> 
>     private void initItems() {
> ```

Maybe this could be better? 
```
    private void initItems() {
        items.clear();
        StringBuilder builder=new StringBuilder();
        for (char c = 'a'; c <= 'z'; c++) {
            for (int i = 0; i < 100; i++) {
                builder.setLength(0);
                items.add(builder.append(c).append(i).toString());
            }
        }
    }
```
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 72 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-Lcdl8Dd1WzL_14m8mEe:-Lcdl8Dd1WzL_14m8mEf:b-7gf65q) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L72)):*
> ```Java
>     }
> 
>     private void itemHandling(SelectionType selectionType, String input) {
> ```

When calling with delay set to true, we are not waiting the 2 seconds, specified in the UI test for `newItemHandling` method.  Also, I think it's more important to check the `Combobox` value, rather than Labels (like is it null, when `Value Label`)
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 116 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-LcdisyN5SBHJrNc8FBh:-LcdisyN5SBHJrNc8FBi:b24voh9) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L116)):*
> ```Java
>     }
> 
>     private void assertThatSelectedValueIs(String value) {
> ```

This is misleading. Call from the beginning of `itemHandling` verifies the value of what? The Combobox value at that point is null, not `ValueLabel`. I would rename the method to something like `asserValueLabelValueIs` and separate method  for checking Combobox value with  assertion on `comboBoxElement.getText/combobxElement.getValue`
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 117 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-LcdkKLo56NEW7hfJACe:-LcdkKLo56NEW7hfJACf:b-y1n07i) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L117)):*
> ```Java
> 
>     private void assertThatSelectedValueIs(String value) {
>         sleep(1000);
> ```

Also, the first time sleep is not needed at all, so I would call sleep before the asserThatSelectedValueIs, if it's  needed
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 120 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-Lcdl-P054r0uZgE4ePE:-Lcdl-P054r0uZgE4ePF:b-yymibg) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L120)):*
> ```Java
>         valueLabelElement = $(LabelElement.class).id("value-label");
>         String valueLabel = valueLabelElement.getText();
>         assertTrue("Selected combobox item should be " + value + ".",
> ```

String.format might be better in this case


<!-- Sent from Reviewable.io -->

2019-04-17 06:27 UTC, ZheSun88 reviewed
as discussed, removed the ticket reference #10915 

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412#-:-LcdyCeH6tu0OyEL_jUe:b9kwod1)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @anasmi and @pleku)

___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRound.java, line 80 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-Lcdidjh-3ksMtIpMaa0:-LcdyTDj1NoPD0oIwqhR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRound.java#L80)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Maybe this could be better? 
```
    private void initItems() {
        items.clear();
        StringBuilder builder=new StringBuilder();
        for (char c = 'a'; c <= 'z'; c++) {
            for (int i = 0; i < 100; i++) {
                builder.setLength(0);
                items.add(builder.append(c).append(i).toString());
            }
        }
    }
```
</blockquote></details>

Done.
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 72 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-Lcdl8Dd1WzL_14m8mEe:-LcdyVaB4pvLhw9oGD9U:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L72)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

When calling with delay set to true, we are not waiting the 2 seconds, specified in the UI test for `newItemHandling` method.  Also, I think it's more important to check the `Combobox` value, rather than Labels (like is it null, when `Value Label`)
</blockquote></details>

Done.
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 116 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-LcdisyN5SBHJrNc8FBh:-LcdyXDW0QjeKCu7q1aL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L116)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

This is misleading. Call from the beginning of `itemHandling` verifies the value of what? The Combobox value at that point is null, not `ValueLabel`. I would rename the method to something like `asserValueLabelValueIs` and separate method  for checking Combobox value with  assertion on `comboBoxElement.getText/combobxElement.getValue`
</blockquote></details>

Done.
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 117 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-LcdkKLo56NEW7hfJACe:-LcdyYZ31BU4Mh34AmPR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L117)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Also, the first time sleep is not needed at all, so I would call sleep before the asserThatSelectedValueIs, if it's  needed
</blockquote></details>

Done.
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 120 at r27](https://reviewable.io/reviews/vaadin/framework/11412#-Lcdl-P054r0uZgE4ePE:-LcdyZJV488I8LpU2TIl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8bd2e13225b5eea0a4d058e526ade5b0d5e18a79/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L120)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

String.format might be better in this case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-17 06:38 UTC, anasmi requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @pleku and @ZheSun88)

___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 112 at r28](https://reviewable.io/reviews/vaadin/framework/11412#-LcdzsNO5sZh1eV4q2PB:-LcdzsNO5sZh1eV4q2PC:b66ljmu) ([raw file](https://github.com/vaadin/framework/blob/674caa9dd2c88f4c1dabca2cb70fe5997f40ed7d/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L112)):*
> ```Java
>         // re-add the same value and select
>         sendKeysToInput(input);
>         performSelect(selectionType);
> ```

Should we also add here the block as it called after reset?
```
        if (delay) {
            sleep(2000);
        }
```


<!-- Sent from Reviewable.io -->

2019-04-17 06:47 UTC, ZheSun88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @anasmi and @pleku)

___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java, line 112 at r28](https://reviewable.io/reviews/vaadin/framework/11412#-LcdzsNO5sZh1eV4q2PB:-Lce2J-z9DFsuKQkVIpZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/674caa9dd2c88f4c1dabca2cb70fe5997f40ed7d/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxAddNewItemAndResetProviderAtSameRoundTest.java#L112)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Should we also add here the block as it called after reset?
```
        if (delay) {
            sleep(2000);
        }
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-17 06:50 UTC, anasmi approved these changes
> Reviewed 1 of 1 files at r26, 1 of 3 files at r27, 1 of 2 files at r28, 1 of 1 files at r29.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-17 09:12 UTC, anasmi approved these changes
> Reviewed 1 of 1 files at r30.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-24 10:26 UTC, TatuLund approved these changes
> Reviewed 2 of 2 files at r31.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11412)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-04-24 10:28 UTC, merged