Issue11288expanded
vaadin/framework pull request #11438
Opened 2019-01-25 14:54 UTC by Ansku

Updated row and spacer handling for Escalator.

Work in Progress. See commit message.

Related to: #11288

2019-05-31 14:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/framework?pullRequest=11438) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/framework?pullRequest=11438) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/framework?pullRequest=11438) it.</sub>

2019-06-28 06:05 UTC, ZheSun88 commented
The failed two tests will be fixed by #11640

2019-07-16 09:50 UTC, pleku commented
To be rebased on top of master after https://github.com/vaadin/framework/pull/11345 is merged.

(ping @Ansku)

2019-07-17 11:33 UTC, pleku requested changes
> Reviewed 2 of 10 files at r1, 2 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 4 of 17 files reviewed, 23 unresolved discussions (waiting on @Ansku and @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11438#-LjzON1UEw0QRszaTPHx:-LjzON1UEw0QRszaTPHy:b-5533tl) (no related file):*
>  For example opening or closing details rows doesn't
> require checking the overall content validity beyond the details row
> itself anymore, but some repositioning at most. There are also no longer
> orphaned spacers without corresponding DOM rows.

Not entirely sure what is meant with "overall content validity", but closing a details row should always cause rechecking of the viewport for the possible need of more rows to be renderer. This is something that cannot be "optimized" away since it is very possible to
1) open a big details row
2) scroll down, cause new rows to be fetched
3) close big details row
-> new rows are not rendered

---
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 65 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzPWK44oGD1oIr5dbP:-LjzPWK44oGD1oIr5dbQ:b9i2vok) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L65)):*
> ```
>     /* Registration for spacer visibility change handler. */
> ```
This comment brings no value as it just repeats the variable name.
Remove the comment or describe reasoning or functionality instead of repetition of name.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 76 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzRcxn27i4ptC5nSNH:-LjzRcxn27i4ptC5nSNI:b-pkbu9g) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L76)):*
> ```
> delayed alert that details have been refreshed
> ```
again, just repeating the variable names but not the reasoning for the variables, could be removed instead of repeating
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 79 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzRLLe9TMBH4hwzZgn:-LjzRLLe9TMBH4hwzZgo:bu42l8h) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L79)):*
> ```
>  private ScheduledCommand delayedDetailsRefreshedCommand = () -> {
> ```
I would like to see this created & scheduled inside the calling method instead of variable, now it makes the code more difficult to understand since of the split up, and it is not called that many times
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 80 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzQW-v2RwLYS8GtF5P:-LjzQW-v2RwLYS8GtF5Q:b-dl84j1) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L80)):*
> ```
> detailsRefreshed(delayedDetailsRefreshed);
> ```
Bad method name, commenting here since I have no idea where the method is yet
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 85 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzS-dj1BZCXtnFRs-H:-LjzS-dj1BZCXtnFRs-I:bmw2c02) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L85)):*
> ```
> /* variables for triggering a delayed re-positioning in Escalator */
> ```
again the same, this adds no value in addition to the variable names
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 87 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzU5bb6QOcbUyESCU_:-LjzU5bb6QOcbUyESCUa:b-brqa3k) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L87)):*
> ```
>     private boolean delayedRepositioningTriggered = false;
>     private Integer delayedRepositioningStart = null;
>     private Integer delayedRepositioningEnd = null;
> ```
Is there a good reason to introduce the `boolean` and use `Integer`? Instead of e.g. using `int` and `-1` for both for not triggered values, since those have to be defined I presume ?
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 89 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzS8RD2SuhWez37Drz:-LjzS8RD2SuhWez37Ds-:b-4i76n9) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L89)):*
> ```
>    private ScheduledCommand delayedRepositioningCommand = () -> {
> ```
I would like to see this created & scheduled inside the calling method instead of variable, now it makes the code more difficult to understand since of the split up, and it is not called that many times
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 94 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzT9vI0bYxs_2c_AFr:-LjzT9vI0bYxs_2c_AFs:byi464y) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L94)):*
> ```
>         if (getWidget().getEscalator().getVisibleRowRange().intersects(Range
>                 .between(delayedRepositioningStart, delayedRepositioningEnd))) {
> ```
Possible `null` values passed to `Range between(final int start, final int end)` which accepts `int` so I'm not even sure what will happen ... confusing anyway so please fix
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 108 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljzcurb0a99C3SzWA0e:-Ljzcurb0a99C3SzWA0f:binl3i9) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L108)):*
> ```
> removing
> ```
This name could be better, now it is a bit too generic
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 118 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVC9o8acILSY_B4jo:-LjzVC9o8acILSY_B4jp:b16jbvl) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L118)):*
> ```
> public void resetDataAndSize(int estimatedNewDataSize) 
> ```
You've introduced bunch of new state variables, should those be cleared now here too ?
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 127 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVN5OEy2zOJeNosAz:-LjzVN5OEy2zOJeNosB-:b-msdn10) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L127)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             if (!getState().hasDetailsGenerator) {
>                 triggerDelayedDetailsRefreshedCommand(false);
>                 return;
>             }
> ```
</details>

I don't understand what happens here. Why is the commend triggered with `false` ? Best way to answer would be probably to rename the method to  [...]

2019-07-17 11:58 UTC, pleku requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 5 of 17 files reviewed, 29 unresolved discussions (waiting on @Ansku)

___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3819 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjziGAX9z_t3OZ1_Nb4:-LjziGAX9z_t3OZ1_Nb5:bnuk39a) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3819)):*
> ```
>                 if (!detailsWidget.isAttached()) {
>                     setParent(detailsWidget, Grid.this);
>                 }
> ```
This seems a bit dubious, where is it done now ???
Why is everything else created/done here but the widget not attached properly to GWT widget hierarchy ?
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3848 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzkwKU1XYfyfdH-rCi:-LjzkwKU1XYfyfdH-rCj:b-qlcpq4) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3848)):*
> ```
> Scheduler.get().scheduleFinally(() -> {
> ```
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3850 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzjhRyEEXgF_ou9tYM:-LjzjhRyEEXgF_ou9tYN:b-23p7es) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3850)):*
> ```
> getElement().isOrHasChild(spacer.getElement())
> ```
Isn't is just easier to check if the `spacer.getElemet().getParentElement()` returns `null` ? Why do you want to traverse the tree between the grid element and the spacer ? Or any other parent element that can be accessed here to verify that the spacer is in the DOM ?
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3855 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzkS5h5iqqHqxxQlFg:-LjzkS5h5iqqHqxxQlFh:b3picyl) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3855)):*
> ```
> confirmedContentHeight != contentHeight
> ```
This could be instead `confirmedContentHeight > 0` similarly as above ?
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3865 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljzm4HK1Gt6uoF0AiSc:-Ljzm4HL9HC5oQesRDps:b-cvmv0s) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3865)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                                 if (getHeightMode() == HeightMode.UNDEFINED) {
>                                     setHeightByRows(getEscalator().getBody()
>                                             .getRowCount());
>                                 }
> ```
</details>

What does this bit do ???

I know it is already here from before (couple lines down), but seems very dubious. Seems like the mode is just changed from here and I would think it definitely should not ?

Maybe both bits should should be refactored to a method instead of code duplication here
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9216 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzhmUA26CpeENu8LCa:-LjzhmUA26CpeENu8LCb:bwg6obz) ([raw file](https://github.com/vaadin/framework/blob/32aa5afc0217a767e85dd579525da5a2eb1163d9/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9216)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>             }
> 
>             if (getEscalatorInnerHeight() != autoColumnWidthsRecalculator.lastCalculatedInnerHeight) {
>                 Scheduler.get().scheduleFinally(() -> {
>                     // Trigger re-calculation of all row positions.
>                     RowContainer.BodyRowContainer body = getEscalator()
>                             .getBody();
>                     if (!body.isAutodetectingRowHeightLater()) {
>                         body.setDefaultRowHeight(body.getDefaultRowHeight());
>                     }
>                 });
>             }
> ```
</details>

Why was this removed ???
What triggers recalculation of things if more rows should be rendered ?


<!-- Sent from Reviewable.io -->

2019-07-17 13:52 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 5 of 17 files reviewed, 29 unresolved discussions (waiting on @Ansku and @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11438#-LjzON1UEw0QRszaTPHx:-LjziAnz4kAMT955RC88:by0e5ok) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  For example opening or closing details rows doesn't
> require checking the overall content validity beyond the details row
> itself anymore, but some repositioning at most. There are also no longer
> orphaned spacers without corresponding DOM rows.

Not entirely sure what is meant with "overall content validity", but closing a details row should always cause rechecking of the viewport for the possible need of more rows to be renderer. This is something that cannot be "optimized" away since it is very possible to
1) open a big details row
2) scroll down, cause new rows to be fetched
3) close big details row
-> new rows are not rendered
</blockquote></details>

There are always enough rows to fill the entire viewport (as long as those rows exist to start with) whether or not any of the details rows are open, and there are checks to ensure gaps aren't left behind. "Extra" rows are prioritized to be placed below the viewport, so closing a details row simply brings them higher up but their content remains the same. If there aren't rows below, that's because we are already scrolled to the bottom (in which case the "extra" rows are above the viewport) and the only thing to do is to switch the viewport up and again the rows that slide into view don't require updating. Because populating happens with delay we can't know how high the details rows are going to end up being, so dropping the "extra" rows wouldn't be trivial even if we wanted to go there.

---
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 65 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzPWK44oGD1oIr5dbP:-LjzjqBD9v9AFSvN9uP0:b-fw47mw) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L65)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>     /* Registration for spacer visibility change handler. */
> ```
This comment brings no value as it just repeats the variable name.
Remove the comment or describe reasoning or functionality instead of repetition of name.
</blockquote></details>

Hm, I already fixed this once, must have got lost in all the rebasing. Will do.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 80 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzQW-v2RwLYS8GtF5P:-LjzkIlF2dxtrrXFvbZi:b-ee3114) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L80)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> detailsRefreshed(delayedDetailsRefreshed);
> ```
Bad method name, commenting here since I have no idea where the method is yet
</blockquote></details>

That's an existing protected method in Grid, I agree that the name is bad but extending applications may rely on it.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 87 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzU5bb6QOcbUyESCU_:-LjznyXXD1bbLSFQs7O5:b-y3wzxa) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L87)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>     private boolean delayedRepositioningTriggered = false;
>     private Integer delayedRepositioningStart = null;
>     private Integer delayedRepositioningEnd = null;
> ```
Is there a good reason to introduce the `boolean` and use `Integer`? Instead of e.g. using `int` and `-1` for both for not triggered values, since those have to be defined I presume ?
</blockquote></details>

I added that because it's possible to add a -1 index spacer, but I'm not too sure if that usage ever goes through DetailsManagerConnector.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 94 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzT9vI0bYxs_2c_AFr:-LjzoSWGAMXsTz1KP0DW:b-12zrn7) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L94)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>         if (getWidget().getEscalator().getVisibleRowRange().intersects(Range
>                 .between(delayedRepositioningStart, delayedRepositioningEnd))) {
> ```
Possible `null` values passed to `Range between(final int start, final int end)` which accepts `int` so I'm not even sure what will happen ... confusing anyway so please fix
</blockquote></details>

It should not be possible to get here without the values being non-null but I'll think about a better way to show that.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 108 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljzcurb0a99C3SzWA0e:-Ljzojcl6gMDbnLj_6Zw:b-eh0isp) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L108)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> removing
> ```
This name could be better, now it is a bit too generic
</blockquote></details>

I'll have to test if that's even needed anymore but I'll rename if it turns out it is still necessary.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 118 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVC9o8acILSY_B4jo:-Ljzp45mBfBxOD7KBl6s:bka2d1f) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L118)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> public void resetDataAndSize(int estimatedNewDataSize) 
> ```
You've introduced bunch of new state variables, should those be cleared now here too ?
</blockquote></details>

Good question, have to investigate. This method doesn't ever called after initialization in the tests I've been working with.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 127 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVN5OEy2zOJeNosAz:-LjzpYTi91uBUdgU2zu6:b-9e301g) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L127)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>             if (!getState().hasDetailsGenerator) {
>                 triggerDelayedDetailsRefreshedCommand(false);
>                 return;
>             }
> ```
I don't understand what happens here. Why is the commend triggered with `false` ? Best way to answer would be probably to rename the method to be more descriptive, like `refreshDetails
</blockquote></details>

Your suggestion got mostly left out so I'm not sure where you were going with it, but it's called with false because nothing in the preceding code suggests that Grid should need to trigger s [...]

2019-07-17 16:13 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 4 of 17 files reviewed, 29 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 65 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzPWK44oGD1oIr5dbP:-Lk-dkHq8w29UeFLE-Sg:b-fsijxj) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L65)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Hm, I already fixed this once, must have got lost in all the rebasing. Will do.
</blockquote></details>

Comment updated.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 76 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzRcxn27i4ptC5nSNH:-Lk-dmQXADA-pFCAj5G1:b-lhot1c) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L76)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> delayed alert that details have been refreshed
> ```
again, just repeating the variable names but not the reasoning for the variables, could be removed instead of repeating
</blockquote></details>

Comment and variable names updated.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 79 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzRLLe9TMBH4hwzZgn:-Lk-egJP3ppYxahJiwKT:b-altfic) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L79)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>  private ScheduledCommand delayedDetailsRefreshedCommand = () -> {
> ```
I would like to see this created & scheduled inside the calling method instead of variable, now it makes the code more difficult to understand since of the split up, and it is not called that many times
</blockquote></details>

Moved as requested.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 80 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzQW-v2RwLYS8GtF5P:-Lk-dtGW334-pMEDyuox:b-9uwmqi) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L80)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

That's an existing protected method in Grid, I agree that the name is bad but extending applications may rely on it.
</blockquote></details>

Not updated, but moved within the calling method as requested.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 85 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzS-dj1BZCXtnFRs-H:-Lk-e1cWE0lzeLHAaLjE:b-fsijxj) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L85)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> /* variables for triggering a delayed re-positioning in Escalator */
> ```
again the same, this adds no value in addition to the variable names
</blockquote></details>

Comment updated.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 89 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzS8RD2SuhWez37Drz:-Lk-euBU5v4CGaQHOrkE:b-altfic) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L89)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>    private ScheduledCommand delayedRepositioningCommand = () -> {
> ```
I would like to see this created & scheduled inside the calling method instead of variable, now it makes the code more difficult to understand since of the split up, and it is not called that many times
</blockquote></details>

Moved as requested.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 94 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzT9vI0bYxs_2c_AFr:-Lk-eyz5A-Tstuz7X6du:b-h56tg2) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L94)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

It should not be possible to get here without the values being non-null but I'll think about a better way to show that.
</blockquote></details>

Actually, I think the moving of the command itself already clarified that. Please tell if you'd like further clarifications there.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 108 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljzcurb0a99C3SzWA0e:-Lk-f90N9NFmMrbsGUxx:b52ooly) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L108)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I'll have to test if that's even needed anymore but I'll rename if it turns out it is still necessary.
</blockquote></details>

Didn't have time to test manually but I removed it experimentally and I expect the validation build will tell us if something broke.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 118 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVC9o8acILSY_B4jo:-Lk-fJ-jCHdLXbTBAP7Y:bxifjn6) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L118)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Good question, have to investigate. This method doesn't ever called after initialization in the tests I've been working with.
</blockquote></details>

As above, added experimentally, can't see any reason why they shouldn't be here.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 127 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVN5OEy2zOJeNosAz:-Lk-fRdiDIAGbKlvSHIG:bjik652) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L127)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Your suggestion got mostly left out so I'm not sure where you were going with it, but it's called with false because nothing in the preceding code suggests that Grid should need to trigger scrollToRow or other pending operations again. If nothing else calls the method with true before the scheduleFinally is actually triggered Grid is simply told to clean out those operations. I can create separate methods for true and false if you think that makes the code more readable, but it's a bit tricky thing naming-wise, since the false doesn't guarantee that Grid won't be alerted to trigger those pending methods instead of just cleaning them out. Would renaming it to detailsAddedOrUpdated(boolean) be more informative? On the downside that would remove from the calling methods [...]

2019-07-18 09:20 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 3 of 17 files reviewed, 29 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 118 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVC9o8acILSY_B4jo:-Lk3LysF3l5z0wzAacA5:bpx8a9r) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L118)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

As above, added experimentally, can't see any reason why they shouldn't be here.
</blockquote></details>

Right. This was called at sorting as well, and the cleanup actually breaks a whole lot. Seems to be safer to not attempt any cleanup here at all since all we have to work with is an estimate of the expected row count, the other methods should make sure the cleanup and refresh happen properly.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 226 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzLkX43x0ce_KkKdaf:-Lk3NJH9AmnI6oZBamX0:bexr6nw) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L226)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Teemu S-A told me once that deferred causes flickering with Grid and should be avoided at all costs. Finally has done the trick this far (when it can't have been avoided altogether) so I haven't had a reason to deviate from that instruction. Whether layouting has been done or not should actually be secondary here, there are more delays down the line, but if the scrolling is triggered before resizing the refresh callback (which is part of the confusing retry functionality)  is also triggered before the resizing actually happens and the row we are supposed to scroll to might not even be visible afterwards.
</blockquote></details>

Refactored into an inner class as requested, comment moved to JavaDoc.


<!-- Sent from Reviewable.io -->

2019-07-18 11:22 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 29 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 108 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljzcurb0a99C3SzWA0e:-Lk3nna45a3yhWzuqNMT:berqss4) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L108)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Didn't have time to test manually but I removed it experimentally and I expect the validation build will tell us if something broke.
</blockquote></details>

All tests still pass after this change.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 118 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzVC9o8acILSY_B4jo:-Lk3o80k1SI_mFK0Y4sa:berqss4) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L118)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Right. This was called at sorting as well, and the cleanup actually breaks a whole lot. Seems to be safer to not attempt any cleanup here at all since all we have to work with is an estimate of the expected row count, the other methods should make sure the cleanup and refresh happen properly.
</blockquote></details>

All tests still pass after this change.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3819 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjziGAX9z_t3OZ1_Nb4:-Lk3baXTE8BWVT7DavLJ:bstynmt) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3819)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

This check *shouldn't* be needed, but it caused a lot of client side exceptions when I started working with this. The DetailsManagerConnector cleanup *should* work properly now and make this check irrelevant, but getting an exception here used to cause very confusing issues elsewhere so I left it in. There is a TODO about this in the external doc but it hasn't been a top priority.
</blockquote></details>

Removed again, easy enough to add back if it's still needed.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3848 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzkwKU1XYfyfdH-rCi:-Lk3bWSn8M4mdwJPwvwD:bjal8q1) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3848)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> Scheduler.get().scheduleFinally(() -> {
> ```

</blockquote></details>

There's no comment here so I assume this one was a misclick.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3850 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzjhRyEEXgF_ou9tYM:-Lk3bQh-1LP1JofVJAT5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3850)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> getElement().isOrHasChild(spacer.getElement())
> ```
Isn't is just easier to check if the `spacer.getElemet().getParentElement()` returns `null` ? Why do you want to traverse the tree between the grid element and the spacer ? Or any other parent element that can be accessed here to verify that the spacer is in the DOM ?
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3855 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzkS5h5iqqHqxxQlFg:-Lk3bNPC8NxKRiJSjSUv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3855)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> confirmedContentHeight != contentHeight
> ```
This could be instead `confirmedContentHeight > 0` similarly as above ?
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9216 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzhmUA26CpeENu8LCa:-Lk3juIn4Z9GTJzojcUn:btj0xo6) ([raw file](https://github.com/vaadin/framework/blob/32aa5afc0217a767e85dd579525da5a2eb1163d9/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9216)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

That was removed because it's a relatively recent bubblegum fix to an issue that doesn't seem to be an issue anymore. Or at least the regression test still works. That thing never should have been necessary, it's a symptom of the "wait and try again" culture that is rampant within the old version, because that just happens to be the only way to get around the frequent timing issues without a big rewrite like this.
</blockquote></details>

Tested manually as well, multi-header Grid within another Grid's details row is displayed properly even without this workaround.
___
*[shared/src/main/java/com/vaadin/shared/ui/grid/DetailsManagerState.java, line 25 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzIvd65SCf86FxOQ72:-Lk3n8Cd0z9jI2dwsPx0:bpg94t) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/shared/src/main/java/com/vaadin/shared/ui/grid/DetailsManagerState.java#L25)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Couldn't figure out what to write there that wouldn't be along the lines of "informs client-side whether there is a details generator" which kind of feels like just repeating the variable name again.

I know that the = false is unnecessary but personally I find it more readable to have there. Sure, everyone who writes Java a lot remembers that boolean is false by default, but I prefer things to be understandable even for people who don't deal with Java a lot. It's not a very costly thing to set it explicitly. Can remove if you really want, of course.
</blockquote></details>

JavaDoc added.


<!-- Sent from Reviewable.io -->

2019-07-18 11:44 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 29 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 680 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzfmUvCtAIR-70fLaQ:-Lk3t25YCue9DAI321PJ:b-dzlh4i) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L680)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Didn't have time to check yet, still on TODO list.
</blockquote></details>

It's called through Escalator's setSpacer for every spacer with non-zero height that doesn't exist yet so should indeed be covered.


<!-- Sent from Reviewable.io -->

2019-07-18 12:12 UTC, pleku requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 2 of 17 files reviewed, 49 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java, line 145 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzsF4l8BDRHR1GLfA5:-LjzsF4l8BDRHR1GLfA6:bxzccd0) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java#L145)):*
> ```
>         void updateRowPositions(int index, int numberOfRows);
> ```
Stylenit: missing unnecessary `public`, which is used for every other method. I do hate it but it is used for consistency
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2115 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzujF94A4MpbvdN3vD:-LjzujF94A4MpbvdN3vE:b-94abzu) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2115)):*
> ```
>          * Triggers delayed auto-detection of default row height if it hasn't
>          * been set by that point and the Escalator is both attached and
>          * displayed.
> ```
I had to search for what sets `display: none`, might have been good to mention it here that hidden (spacer) elements have that property ? 
Or another alternative, mayhaps better, could be to have a dedicated method `isDisplayed()` that is used in all places, similarly as `isAttached()`. Would make the code more cleaner.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2778 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk30Jc00J61QGkT-X8C:-Lk30Jc00J61QGkT-X8D:b-1gzcv2) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2778)):*
> ```
>             final double viewportOffsetBottom = scrollTop + sectionHeight
>                     - getRowTop(
>                             getTopRowLogicalIndex() + visualRowOrder.size());
> ```

`getRowTop( )` ? For _offset bottom_, shouldn't it use _row bottom_ ? Otherwise it might be that the last row is shown fully, but the calculated value claims that is only partially visible ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2787 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-27oLCnSatCajA30M:-Lk-27oMEGMDN4nyLCDo:b-7f0i5o) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2787)):*
> ```
> , scrolling up.
> ```

Would have added this before _there is empty room at top_ now I first read it as this method would start scrolling ...
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2795 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-2RbG5eHxHhbJ3Ykx:-Lk-2RbG5eHxHhbJ3Yky:b-6k3xjm) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2795)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>                  * We can ignore spacers here, because maximal amount of rows
>                  * within viewport means that there are enough rows to fill the
>                  * whole viewport even if all spacers are removed. Consequently,
>                  * even if there are spacers, repositioning this many rows won't
>                  * cause us to run out of rows at the bottom, and we can't know
>                  * what height the spacers have before adding them in any case.
>                  *
> ```
</details>


This could be mayhaps reworded to be a bit more understandable, I'm struggling a lot to see the point in this explanation.
Something like I saw in a comment/commit message would be more beneficial, like
"Ignoring spacers on purpose, there is smaller trade-off in adding more than necessary rows if there will be spacers visible".
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2810 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-3lDM4Xjn2CGOpsew:-Lk-3lDN0ntvrlNi5VB3:b1kps12) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2810)):*
> ```
> // add the extra row if there is room for it
> ```

I presume the _extra_ is for the tabbing purpose mentioned above, could have just said so.

But I don't what does the _room for it mean_ ? Should it be about _if there is still rows to be added ? As it is stated in the code couple lines below. Now this step & comment is just confusing me
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2829 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-8AGS0qnlrC3EYruw:-Lk-8AGS0qnlrC3EYrux:b-bm3jav) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2829)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>                 /*
>                  * Calculate the logical index for insertion point based on how
>                  * many rows would be needed to fill the gap. Don't just
>                  * calculate which row belongs to this position or we might end
>                  * up with duplicates or skipping some content if there are any
>                  * issues. A gap at either end is simpler to debug.
>                  */
>                 final int logicalRowIndex = getTopRowLogicalIndex()
>                         - rowsToFillTheGap;
> ```
</details>


I would have named this variable `newTopRowLogicalIndex` instead.

The comment part after "Don't.." feels a bit out of place since it is like replying to some old implementation. I also don't understand how duplicates come into play ... just confusing comments
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2834 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-92zTBI3eSvyDNPBS:-Lk-92zTBI3eSvyDNPBT:bsmukh2) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2834)):*
> ```
>  re-purpose 
> ```

I think the correct term is recycle or something that is more closer to escalator ... could just remove this comment
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2839 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-9E-ZB67Cn9XhhVWn:-Lk-9E-ZB67Cn9XhhVWo:bgdxegn) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2839)):*
> ```
>                 // rows were re-purposed to the top so the logical index is also
>                 // the new top row logical index
> ```

IMO unnecessary addition
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2844 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk2zB6R3AAHlaPESfwv:-Lk2zB6R3AAHlaPESfww:b61bnv6) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2844)):*
> ```
>             } else if (viewportOffsetBottom > 0
>                     && (viewportOffsetTop + nextRowBottomOffset <= 0)) {
>                 /*
> ```

As said above, `viewportOffsetBottom` doesn't at this point guarantee that there is empty room at the bottom.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2866 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk34-YZ05nni-j1bCV-:-Lk34- [...]

2019-07-18 15:58 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 49 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java, line 145 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzsF4l8BDRHR1GLfA5:-Lk4273d24aWwadzEgeB:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java#L145)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>         void updateRowPositions(int index, int numberOfRows);
> ```
Stylenit: missing unnecessary `public`, which is used for every other method. I do hate it but it is used for consistency
</blockquote></details>

Done
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2115 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzujF94A4MpbvdN3vD:-Lk42ZJwEchmcjWEzy0U:boexj3y) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2115)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>          * Triggers delayed auto-detection of default row height if it hasn't
>          * been set by that point and the Escalator is both attached and
>          * displayed.
> ```
I had to search for what sets `display: none`, might have been good to mention it here that hidden (spacer) elements have that property ? 
Or another alternative, mayhaps better, could be to have a dedicated method `isDisplayed()` that is used in all places, similarly as `isAttached()`. Would make the code more cleaner.
</blockquote></details>

That's not actually about hidden spacers, it's for attaching the Grid itself with `display: none` and then turning it visible again. If the calculations are done when the Grid is still hidden some of the defaults will be determined wrong and never checked again. When we skip the calculations entirely while there is nothing to calculate the check will be performed by default when the visibility changes, at which point the defaults get correct values, and we can avoid forcing the calculations just in case when they are not actually needed.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2778 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk30Jc00J61QGkT-X8C:-Lk44pVe0T_PhMumIPbS:b-lnk42f) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2778)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>             final double viewportOffsetBottom = scrollTop + sectionHeight
>                     - getRowTop(
>                             getTopRowLogicalIndex() + visualRowOrder.size());
> ```

`getRowTop( )` ? For _offset bottom_, shouldn't it use _row bottom_ ? Otherwise it might be that the last row is shown fully, but the calculated value claims that is only partially visible ?
</blockquote></details>

No, because `getTopRowLogicalIndex() + visualRowOrder.size()` is the index of the first row _below_ the visual range. There doesn't even need to be a row there in reality (as in the index can be for a row that would fall below the very last row), `getRowTop` works regardless, and this way we don't need to add the row height and spacer height separately. There is no existing `getRowBottom` helper method although I can create one if you want.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2787 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-27oLCnSatCajA30M:-Lk47vX8DgfKcPmFIJQr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2787)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> , scrolling up.
> ```

Would have added this before _there is empty room at top_ now I first read it as this method would start scrolling ...
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2795 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-2RbG5eHxHhbJ3Ykx:-Lk4BCtR4s6rm_tq-DtN:b-qj92pf) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2795)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                  * We can ignore spacers here, because maximal amount of rows
>                  * within viewport means that there are enough rows to fill the
>                  * whole viewport even if all spacers are removed. Consequently,
>                  * even if there are spacers, repositioning this many rows won't
>                  * cause us to run out of rows at the bottom, and we can't know
>                  * what height the spacers have before adding them in any case.
>                  *
> ```

This could be mayhaps reworded to be a bit more understandable, I'm struggling a lot to see the point in this explanation.
Something like I saw in a comment/commit message would be more beneficial, like
"Ignoring spacers on purpose, there is smaller trade-off in adding more than necessary rows if there will be spacers visible".
</blockquote></details>

Reworded.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2810 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-3lDM4Xjn2CGOpsew:-Lk4BEqU7fh2_NcldbZ9:bfvh688) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2810)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> // add the extra row if there is room for it
> ```

I presume the _extra_ is for the tabbing purpose mentioned above, could have just said so.

But I don't what does the _room for it mean_ ? Should it be about _if there is still rows to be added ? As it is stated in the code couple lines below. Now this step & comment is just confusing me
</blockquote></details>

It means that we don't add a row with index -1 just to have a buffer row, we only need one as long as there are more rows to scroll to. Added a clarifying sentence to the previous comment section and switched to use 'buffer row' instead of 'extra row'.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2829 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-8AGS0qnlrC3EYruw:-Lk4D_pA18veQBq8go5X:bprwn7c) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2829)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 /*
>                  * Calculate the logical index for insertion point based on how
>                  * many rows would be needed to fill the gap. Don't just
>                  * calculate which row belongs to this position or we might end
>                  * up with duplicates or skipping some content if there are any
>                  * issues. A gap at either end is simpler to debug.
>                  */
>                 final int logicalRowIndex = getTopRowLogicalIndex()
>                         - rowsToFillTheGap;
> ```

I would have named this variable `newTopRowLogicalIndex` instead.

The comment part after "Don't.." feels a bit out of place since it is like replying to some old implementation. I also don't understand how duplicates come into play ... just confusing com [...]

2019-07-18 18:07 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 49 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2972 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk3zRyf3O0xIf095Gx5:-Lk5Fryi2TpFg38VuML5:bf3tsed) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2972)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Good point. The gap should actually appear to the bottom because `moveAndUpdateEscalatorRows` is too clever for its own good, but a gap should definitely appear if the removed spacer is large enough (how large, exactly, depends on circumstances). Will add scroll position adjusting logic tomorrow or see if I can get this use case combined with the first use case in order to get rid of duplicate logic.
</blockquote></details>

Got the experimental combining of use cases done, none of the tests broke locally at least but the validation build will take a while still.


<!-- Sent from Reviewable.io -->

2019-07-18 18:55 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 49 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2972 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk3zRyf3O0xIf095Gx5:-Lk5Qw9ZD8xfVqpUS_Te:b-dxvkiq) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2972)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Got the experimental combining of use cases done, none of the tests broke locally at least but the validation build will take a while still.
</blockquote></details>

Validation build completed successfully.


<!-- Sent from Reviewable.io -->

2019-07-19 10:29 UTC, pleku requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 61 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3043 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7jNhCAHjwv6Wnx103:-Lk7jNhCAHjwv6Wnx104:b-8mston) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3043)):*
> ```
> if (numberOfRows <= 0) {
> ```
Is it really possible that there can be a negative amount of rows ??

If it "should never happen" (TM), how about having an assert after this that gives a valid message that "things are broken now" or such. 
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3081 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7k2_x1pTyY2ufFu5S:-Lk7k2_x1pTyY2ufFu5T:bct2pbd) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3081)):*
> ```
>              * Currently that's left to be triggered at the end and if any new
>              * spacers exist everything below them is going to be repositioned
>              * again for every spacer addition.
> ```

Probably missing a comma
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3117 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7mh318aIwdfha__Cu:-Lk7mh318aIwdfha__Cv:bp92hqh) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3117)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>                  * to dom or there would be a gap in the visual range. Adding
>                  * new dom rows to the beginning without a gap would require an
>                  * index that equals oldTopRowLogicalIndex (in which case
>                  * newRowsInsertedAboveVisualRange would not be true), and by
>                  * default if we are scrolled down far enough that there are
>                  * rows above the visual range the whole visual range is already
>                  * in use so adding is unlikely in any case.
> ```
</details>


Please do reword this to make some sense
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3169 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7o4GA9UjzIqY_R3Dm:-Lk7o4GA9UjzIqY_R3Dn:b-h69you) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3169)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>                  * Because the insertion point is out of view above the viewport
>                  * in this case, the only thing that should change for the end
>                  * user visually is the scroll handle position and possibly size
>                  * if the insertion is large enough to affect the overall
>                  * content height significantly. Behind the scenes this also
>                  * means that any rows that might need to get re-purposed should
>                  * be taken from the BEGINNING of the visual range. Don't try to
>                  * re-purpose rows from the bottom even if there is excess, they
>                  * are more useful where they are. It is even possible that no
>                  * rows get added to dom or re-purposed at all, if the insertion
>                  * point is at the very beginning of the visual range and the
>                  * dom row count is already at maximum.
> ```
</details>


There is two confusing and long chapters that need rewording, and then the whole point (for the following code bit) in the third chapter.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3201 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7p5yv1PSLjot1NykH:-Lk7p5yv1PSLjot1NykI:b-121cy0) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3201)):*
> ```
>                 // insertion index within the visual range
>                 int visualIndex = index - oldTopRowLogicalIndex;
> ```

Should this be just named as `insertionVisualIndex` and remove the comment ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3237 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7rPdR4jPHm0y3ytie:-Lk7rPdR4jPHm0y3ytif:bq9c77k) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3237)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                      * FIXME: spacers haven't been added yet and they can cause
>                      * escalator contents to shift after the fact in a way that
>                      * can't be countered for here.
>                      *
> ```
</details>


There is no callback to readjust things after spacers have been added for the inserted rows ? 
Should this method even try to consider those ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3242 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7r1qO7vrBv2cfWN5N:-Lk7r1qO7vrBv2cfWN5O:bdxabhu) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3242)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                      * FIXME: verticalScrollbar internal state causes this
>                      * update to fail partially and the next attempt at
>                      * scrolling causes things to jump.
>                      *
> ```
</details>


WHY ? What does "fail partially" mean ?
Could it be related to moving the `scroller.recalculateScrollbarsForVirtualViewport();` to happen after all other updates ?
Previously it was done in the beginning of this method.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3453 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8demLAE6k5BQWhmMG:-Lk8demLAE6k5BQWhmMH:bib003a) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3453)):*
> ```
> final TableRowElement tr = visualRowOrder.get(visualIndex);
> ```

I'm not entirely sure how does GWT compile this to JS, but at least in Java it is slower now since the previous version used `ListIterator` instead.

Is there any good reason why to not keep using it as everything starts from `adjustedVisualTargetIndex` and everything is fetched linearly without any skips or bouncing around for the items ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3470 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8efiBAXQcopwTiC_9:-Lk8efiBAXQcopwTiC_A:bnoyw32) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3470)):*
> ```
> spacer indexes
> ```

for consistency, could add that this means logical indexes
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3551 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8gMcS2uAvncaUU67k:-Lk8gMcS2uAvncaUU67l:b-syrwz2) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3551)):*
> ```
>                     // didn't change, rows below the shift need to be moved up
>                     // but the shifted rows [...]

2019-07-19 13:29 UTC, pleku requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 79 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3686 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9Hh8VDiN56-B65yXm:-Lk9Hh8VDiN56-B65yXn:bfuyjx7) ([raw file](https://github.com/vaadin/framework/blob/32aa5afc0217a767e85dd579525da5a2eb1163d9/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3686)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             /*
>              * TODO [[spacer]]: these assumptions will be totally broken with
>              * spacers.
>              */
> ```
</details>


Was this fixed now or is this comment just old ? The changes here don't reflect it 
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3748 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8mx9d6UspWnJ0BBm7:-Lk8mx9e2ln5yyk8QAX1:buk33vt) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3748)):*
> ```
> 0
> ```

not sure if it makes any difference in the JS but `0d` would read better in the context
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3754 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8n73qD7Qa_ucWw0LM:-Lk8n73qD7Qa_ucWw0LN:buk33vt) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3754)):*
> ```
> 0
> ```

not sure if it makes any difference in the JS but `0d` would read better in the context
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3858 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8rMypCp-PAAN9GDvI:-Lk8rMypCp-PAAN9GDvJ:b-hxwssb) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3858)):*
> ```
> the added rows and below
> ```

"the added rows and rows below them" ?  
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3861 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8rfsSElnPIYipyL6e:-Lk8rfsSElnPIYipyL6f:b-qgkq4u) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3861)):*
> ```
>                 // TODO: this can lead to moving things around twice in case
>                 // some rows didn't get new dom rows, consider moving this
> ```

Please elaborate what/when case is that ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3893 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk8rok40TKwwciThBis:-Lk8rok40TKwwciThBit:b-tk85ln) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3893)):*
> ```
> assisting with navigation on both sides of the viewport
> ```
"..with tab navigation.."
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3944 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9EPfn5YVKvP-FXwOO:-Lk9EPfn5YVKvP-FXwOP:bb9yu22) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3944)):*
> ```
> convertToVisual(
> ```
Probably it should be `convertLogicalToVisual(`instead
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4024 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9H1p41e-o794yFH8K:-Lk9H1p41e-o794yFH8L:b6i9jkl) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4024)):*
> ```Java
>                  * above the old visual range in turn. This shifts the index
>                  * down even further.
>                  */
> ```

Rest of the method to be reviewed with a clear head

Initial feeling is that it is (like others) too complex and splitting it down to methods that do some parts would be beneficial
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4319 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9I_ut-uWUqORALONd:-Lk9I_ut-uWUqORALONe:b-668apu) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4319)):*
> ```
>     final int visualIndexBottom = oldVisualRangeLength;
> ```

Shouldn't it be length -1 instead?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4329 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9KXY70AVqcaM-tt1S:-Lk9KXY70AVqcaM-tt1T:bq3uu5m) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4329)):*
> ```
>                 // prioritise adding to the bottom so that there's less chance
>                 // for a gap if a details row is closed
> ```

Closed by what / when ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4350 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9LQPf5OPsGheCUYRf:-Lk9LQPf5OPsGheCUYRg:bqckldh) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4350)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                 // prioritise removing rows from above the viewport as they are
>                 // less likely to be needed in a hurry -- the rows below are
>                 // more likely to slide into view when spacer contents are
>                 // updated
> ```
</details>


This feels like a very bad optimization decision and most cases scrolling happens 50-50 to either direction and spacers are not in play at all.

Not sure if it makes a difference though
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4359 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9Mra4CwBgVgu9zOu3:-Lk9Mra4CwBgVgu9zOu4:b7wqgle) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4359)):*
> ```
> visualRowOrder.get(i)
> ```
This loop could be replaced with a list iterator instead
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4363 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9MY1u1l1Je4m1Tmbj:-Lk9MY1u1l1Je4m1Tmbk:b-pguich) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4363)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>                     if (positions.getTop(visualRowOrder.get(i)) <= scrollTop) {
>                         oldFirstVisibleVisualIndex = i;
>                         continue;
>                     }
>                     break;
> ```
</details>


ugh, please reverse into breaking inside the `if` instead and then you don't have to have the `continue` outside it.
I think this is the first time ever I've seen it done this way around ...
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4373 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9N72M1jhJtEnfPSxE:-Lk9N72M1jhJtEnfPSxF:b9wb69x) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4373)):*
> ```
> iter
> ```

I would have gone  for  [...]

2019-07-19 20:23 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 79 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3043 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7jNhCAHjwv6Wnx103:-Lk9FuzZ3rtwk595ZaoQ:biy05vp) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3043)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> if (numberOfRows <= 0) {
> ```
Is it really possible that there can be a negative amount of rows ??

If it "should never happen" (TM), how about having an assert after this that gives a valid message that "things are broken now" or such. 
</blockquote></details>

Even zero "should never happen", added asserts for both.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3081 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7k2_x1pTyY2ufFu5S:-Lk9JE3U6xb4pZbkcUYQ:b-8jb1zs) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3081)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>              * Currently that's left to be triggered at the end and if any new
>              * spacers exist everything below them is going to be repositioned
>              * again for every spacer addition.
> ```

Probably missing a comma
</blockquote></details>

Tweaked.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3117 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7mh318aIwdfha__Cu:-Lk9PYus3r9HqDTyA1cO:be2vfi2) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3117)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                  * to dom or there would be a gap in the visual range. Adding
>                  * new dom rows to the beginning without a gap would require an
>                  * index that equals oldTopRowLogicalIndex (in which case
>                  * newRowsInsertedAboveVisualRange would not be true), and by
>                  * default if we are scrolled down far enough that there are
>                  * rows above the visual range the whole visual range is already
>                  * in use so adding is unlikely in any case.
> ```

Please do reword this to make some sense
</blockquote></details>

:D  Reworded. Also decided to move here the corner case of inserting rows immediately above the visual range when we are scrolled down at least a bit and without a need for new rows.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3169 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7o4GA9UjzIqY_R3Dm:-LkA1IeKEIDuwcKW2Px5:b-khznk2) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3169)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                  * Because the insertion point is out of view above the viewport
>                  * in this case, the only thing that should change for the end
>                  * user visually is the scroll handle position and possibly size
>                  * if the insertion is large enough to affect the overall
>                  * content height significantly. Behind the scenes this also
>                  * means that any rows that might need to get re-purposed should
>                  * be taken from the BEGINNING of the visual range. Don't try to
>                  * re-purpose rows from the bottom even if there is excess, they
>                  * are more useful where they are. It is even possible that no
>                  * rows get added to dom or re-purposed at all, if the insertion
>                  * point is at the very beginning of the visual range and the
>                  * dom row count is already at maximum.
> ```

There is two confusing and long chapters that need rewording, and then the whole point (for the following code bit) in the third chapter.
</blockquote></details>

Reworded quite a bit and moved one corner case to the earlier check. Not sure I got everything you meant, though. It's a lot to read no matter what I do to it and it's getting late so I'm not even sure I make any sense anymore.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3201 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7p5yv1PSLjot1NykH:-LkA2j3SD7tQfqS7KtTQ:bfb8gml) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3201)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 // insertion index within the visual range
>                 int visualIndex = index - oldTopRowLogicalIndex;
> ```

Should this be just named as `insertionVisualIndex` and remove the comment ?
</blockquote></details>

Renamed to `visualTargetIndex` to match other places but left the comment.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3237 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7rPdR4jPHm0y3ytie:-LkA3yiX3ltyd49vWMgH:b-wqh5do) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3237)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                      * FIXME: spacers haven't been added yet and they can cause
>                      * escalator contents to shift after the fact in a way that
>                      * can't be countered for here.
>                      *
> ```

There is no callback to readjust things after spacers have been added for the inserted rows ? 
Should this method even try to consider those ?
</blockquote></details>

No, and I haven't figured out how to create one that would do the trick either. There is no handling for that in the current version either, though, and this is a rather marginal use case (you need to programmatically expand a TreeGrid node that falls within visual range but above the viewport and "extra" rows are prioritized to bottom whenever possible), but it's still a known issue.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 3242 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk7r1qO7vrBv2cfWN5N:-LkA5kjDACI2uCNevUVo:bc620ux) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L3242)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                      * FIXME: verticalScrollbar internal state causes this
>                      * update to fail partially and the next attempt at
>                      * scrolling causes things to jump.
>                      *
> ```

WHY ? What does "fail partially" mean ?
Could it be related to moving the `scroller.recalculateScrollbarsForVirtualViewport();` to happen after all other updates ?
Previously it was done in the beginning of this method.

</blockquote></details>

Honestly, can't remember. The scrollbars can't be recalculated before all other updates, though, because you are going to have all the yet-to-be-removed spacers messing up the calculations. Investigating this again has a TODO on the external doc but it has had a low priority.
___
*[client/src/main/java/com/vaadin/c [...]

2019-08-07 14:33 UTC, pleku requested changes
> Reviewed 1 of 3 files at r13, 1 of 6 files at r15.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 2 of 17 files reviewed, 79 unresolved discussions (waiting on @Ansku and @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11438#-LjzON1UEw0QRszaTPHx:-LlfmTs3-Q39NoF87Cc6:bdmnx2e) (no related file):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

There are always enough rows to fill the entire viewport (as long as those rows exist to start with) whether or not any of the details rows are open, and there are checks to ensure gaps aren't left behind. "Extra" rows are prioritized to be placed below the viewport, so closing a details row simply brings them higher up but their content remains the same. If there aren't rows below, that's because we are already scrolled to the bottom (in which case the "extra" rows are above the viewport) and the only thing to do is to switch the viewport up and again the rows that slide into view don't require updating. Because populating happens with delay we can't know how high the details rows are going to end up being, so dropping the "extra" rows wouldn't be trivial even if we wanted to go there.
</blockquote></details>

Right, so guess the simplified version of the new logic would be:

_The viewport is always filled with enough available rows, and then the details are opened on top of that, meaning closing details rows doesn't need new rows to be added._ 

Right ? 

---
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 87 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzU5bb6QOcbUyESCU_:-LlfnJ261Ix-6m6sfkuj:bhglsjs) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L87)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I added that because it's possible to add a -1 index spacer, but I'm not too sure if that usage ever goes through DetailsManagerConnector.
</blockquote></details>

Please expose that knowledge in the code as comment so that further generations may understand this design decision easily
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 588 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljz_Yci4KdB22rXcrzj:-LlfqG1oENunS9FX9zOK:b-gk29ze) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L588)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Clarified the comment a bit and added spaces to better signify which parts are relevant to the comment.
</blockquote></details>

Based on your comment I would imagine the better variable names would then be 
`previousUpdatedVisibleRowRange` for the field and `currentVisibleRowRange` for the local variable.
Then the comment would be mayhaps simplified to something else too
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 680 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzfmUvCtAIR-70fLaQ:-Llfrb8fDCV9st5bHgGf:bj61hsp) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L680)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

It's called through Escalator's setSpacer for every spacer with non-zero height that doesn't exist yet so should indeed be covered.
</blockquote></details>

mayhaps could add a line to the comment informing that "listeners are added when escalator requests for the details again"
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 130 at r15](https://reviewable.io/reviews/vaadin/framework/11438#-LlfoA1wCwy4BnkIUKso:-LlfoA1wCwy4BnkIUKsp:b6ywqrx) ([raw file](https://github.com/vaadin/framework/blob/4eec9db4f23deb951a5d7b1822addec9d3d33407/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L130)):*
> ```
>                         // have to mark true to trigger the potential scrolling
>                         // attempt
> ```
"have to mark true to..." ? Instead it should say just "have to trigger possible scrolling attempt to keep visual range the same" ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4080 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg0NjeA6RZs3Y7-ZMP:-Llg0NjeA6RZs3Y7-ZMQ:bx4nxqd) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4080)):*
> ```
>                     // calculate first logical index below the old visual range
>                     // rows after the rows are removed
>                     int firstBelow = newTopRowLogicalIndex
> ```
old visual range ? yet it is using the `newTopRowLogicalIndex` ? maybe it should say "calculate logical index for first row not visible after row removals" 
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4091 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg174O1-CK31wntW5d:-Llg174O1-CK31wntW5e:b-7ni2zk) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4091)):*
> ```Java
> 
>                 // add new content from above visual range, if there is any
>                 if (rowsToIncludeFromAbove > 0) {
> ```

Is there any particular reason why rows are moved from below before above ?
Even if there is not, might be sensible to comment why the ordering is like it is 
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4098 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg1TkCBU0uFQMNlOU1:-Llg1TkCBU0uFQMNlOU2:b-qugqes) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4098)):*
> ```
> re-purposing
> ```
NIT: but I'd prefer _recycling_ 
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4098 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg1_15EyF6yydXrNEP:-Llg1_15EyF6yydXrNEQ:bynj7xz) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4098)):*
> ```
>                 // re-purposing updates all relevant row and spacer positions
>                 // but if none happened, rows from below the removal point need
>                 // to be shifted up by the removed amount
> ```
Nitpick: This could be rephrased a lot better
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4102 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg2-WA9E-OxI4UFlmx:-Llg2-WA9E-OxI4UFlmy:bd90fjp) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4102)):*
> ```
>                 if (rowsToIncludeFromAbove <= 0
>                         && rowsToIncludeFromBelow <= 0) {
> ```
Should this also check that there was actually rows removed, using `rowsToRemoveFromDom > 0` ?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4732 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgBPhvC36f0SCj0rR3:-LlgBPhvC36f0SCj0rR4:b-rh999o) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4732)):*
> ```
> (int rowIndex
> ```
Afte [...]

2019-08-07 17:52 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 2 of 17 files reviewed, 79 unresolved discussions (waiting on @Ansku and @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11438#-LjzON1UEw0QRszaTPHx:-Llgcdt3DVr3tb288b19:b-1vijnd) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Right, so guess the simplified version of the new logic would be:

_The viewport is always filled with enough available rows, and then the details are opened on top of that, meaning closing details rows doesn't need new rows to be added._ 

Right ? 
</blockquote></details>

Exactly.

---
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 130 at r15](https://reviewable.io/reviews/vaadin/framework/11438#-LlfoA1wCwy4BnkIUKso:-LlgVqxzCQE8BPUsMV3y:bwm5ceh) ([raw file](https://github.com/vaadin/framework/blob/4eec9db4f23deb951a5d7b1822addec9d3d33407/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L130)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                         // have to mark true to trigger the potential scrolling
>                         // attempt
> ```
"have to mark true to..." ? Instead it should say just "have to trigger possible scrolling attempt to keep visual range the same" ?
</blockquote></details>

The thing is, the scrolling attempt doesn't happen here yet. All this is guaranteed to do immediately, is to mark the flag true. If the scheduled command hasn't been added yet that's done as well, but sometimes that's skipped. The actual triggering happens only when the scheduled command is run.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4080 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg0NjeA6RZs3Y7-ZMP:-Llge8GO3znsYKWDvduH:b-o9y530) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4080)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                     // calculate first logical index below the old visual range
>                     // rows after the rows are removed
>                     int firstBelow = newTopRowLogicalIndex
> ```
old visual range ? yet it is using the `newTopRowLogicalIndex` ? maybe it should say "calculate logical index for first row not visible after row removals" 
</blockquote></details>

That's not the same thing, because we are just about to add more rows below the old range by recycling (some of) the removed rows. It's the logical index of the insertion point. The first row that stays not visible after all the processing is done would be `firstBelow +  rowsToIncludeFromBelow`. And it feels to me that just saying `calculate the logical index of the insertion point` doesn't give enough clues for _why_ that is the logical index of the insertion point, because as you said, it's not intuitive that you need `newTopRowLogicalIndex` if that's the goal. We need the old range, but we need it updated to the new indexes in the moment before any other consequences of the removal have kicked in.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4091 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg174O1-CK31wntW5d:-LlgiO2h69OP7sFxqeyD:ba70et0) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4091)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Is there any particular reason why rows are moved from below before above ?
Even if there is not, might be sensible to comment why the ordering is like it is 
</blockquote></details>

It's the same order as above, where `rowsToIncludeFromBelow` and `rowsToIncludeFromAbove` are calculated. We use the first to come up with the second. Adding rows below is the default, because that means there's no need to scroll. When you remove a row, you don't expect the rows below it to stay in place visually, unless you are already at the bottom. It would be possible to do the recycling in either order, of course, but adding rows above also changes the beginning of the visual range, which would mean more complicated and confusing calculations for the adding rows below bit. In most cases that's the only part that is ever done, so not complicating it saves us from doing some calculations at all. It's already explained in the initial comment block of this section that any new rows are brought in from below by default, but I can add a new comment here if you feel the current explanation is too far away.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4102 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg2-WA9E-OxI4UFlmx:-Llgo9oRDsTPeNu7tUTf:b-xiitpv) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4102)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 if (rowsToIncludeFromAbove <= 0
>                         && rowsToIncludeFromBelow <= 0) {
> ```
Should this also check that there was actually rows removed, using `rowsToRemoveFromDom > 0` ?
</blockquote></details>

If no rows were removed or recycled from within the visual range we shouldn't even be in this section, those use cases were handled earlier.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4732 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgUOevAAbe5XeVHrER:-Llgpq4x2krc8I4pHdj7:b-p5g58) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4732)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should this method return early if requested target is already visible ?
</blockquote></details>

Depends on the chosen destination and padding. The target might be visible but in wrong position.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4745 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg9C_P8-LMj_8eMvw6:-LlgYRRi2rzXG5YvplC5:bwvoezn) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4745)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>             if (rowIndex != -1) {
>                 verifyValidRowIndex(rowIndex);
>             }
> ```
Very confusing pattern. rowIndex -1 is OK and doesn't need validation ? everything will work then ? and I wonder what is the role of `verifyValidRowIndex` here since calling it doesn't have any effect on this method's execution
</blockquote></details>

`verifyValidRowIndex` throws an `IndexOutOfBoundsException` if the given index isn't valid, which would halt the execution of this method. Both the `verifyValidRowIndex` call and the check are old code from `scrollToRowAndSpacer` method, but I'm pretty sure the check was originally added there to work around the special case of the -1 index spacer, which isn't a valid index by default (and would thus cause an exception).
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4754 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg9mPR-CoidFxmlwAW:-Llgr_ZhCg-w_6ZtCVV_:b-4efpp1) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4754)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><block [...]

2019-08-08 00:55 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 79 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 87 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzU5bb6QOcbUyESCU_:-Llidgsv9LPqRwQhsY38:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L87)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please expose that knowledge in the code as comment so that further generations may understand this design decision easily
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 588 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljz_Yci4KdB22rXcrzj:-LlidsEY81xG4j_K3dFA:b2il6un) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L588)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Based on your comment I would imagine the better variable names would then be 
`previousUpdatedVisibleRowRange` for the field and `currentVisibleRowRange` for the local variable.
Then the comment would be mayhaps simplified to something else too
</blockquote></details>

Went with just `updatedVisibleRowRange` since it's already in past tense, but I can add the `previous` if you feel strongly about it.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 680 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzfmUvCtAIR-70fLaQ:-LlieKoT3rPLgftG5XBQ:b-bfyq60) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L680)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

mayhaps could add a line to the comment informing that "listeners are added when escalator requests for the details again"
</blockquote></details>

Added a comment lower down.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 130 at r15](https://reviewable.io/reviews/vaadin/framework/11438#-LlfoA1wCwy4BnkIUKso:-LlidkJQ4TbeTN8XUNxG:b-8jb1zs) ([raw file](https://github.com/vaadin/framework/blob/4eec9db4f23deb951a5d7b1822addec9d3d33407/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L130)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

The thing is, the scrolling attempt doesn't happen here yet. All this is guaranteed to do immediately, is to mark the flag true. If the scheduled command hasn't been added yet that's done as well, but sometimes that's skipped. The actual triggering happens only when the scheduled command is run.
</blockquote></details>

Tweaked.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4080 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg0NjeA6RZs3Y7-ZMP:-LlifFXU9l7u-BY21nQA:b-8jb1zs) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4080)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

That's not the same thing, because we are just about to add more rows below the old range by recycling (some of) the removed rows. It's the logical index of the insertion point. The first row that stays not visible after all the processing is done would be `firstBelow +  rowsToIncludeFromBelow`. And it feels to me that just saying `calculate the logical index of the insertion point` doesn't give enough clues for _why_ that is the logical index of the insertion point, because as you said, it's not intuitive that you need `newTopRowLogicalIndex` if that's the goal. We need the old range, but we need it updated to the new indexes in the moment before any other consequences of the removal have kicked in.
</blockquote></details>

Tweaked.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4091 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg174O1-CK31wntW5d:-LlifINm7NtweSBUSQSs:b-zjc50) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4091)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

It's the same order as above, where `rowsToIncludeFromBelow` and `rowsToIncludeFromAbove` are calculated. We use the first to come up with the second. Adding rows below is the default, because that means there's no need to scroll. When you remove a row, you don't expect the rows below it to stay in place visually, unless you are already at the bottom. It would be possible to do the recycling in either order, of course, but adding rows above also changes the beginning of the visual range, which would mean more complicated and confusing calculations for the adding rows below bit. In most cases that's the only part that is ever done, so not complicating it saves us from doing some calculations at all. It's already explained in the initial comment block of this section that any new rows are brought in from below by default, but I can add a new comment here if you feel the current explanation is too far away.
</blockquote></details>

Added a small comment.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4098 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg1_15EyF6yydXrNEP:-LlifP3LC1kacmNsrz5f:b-ta2j89) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4098)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 // re-purposing updates all relevant row and spacer positions
>                 // but if none happened, rows from below the removal point need
>                 // to be shifted up by the removed amount
> ```
Nitpick: This could be rephrased a lot better
</blockquote></details>

Tweaked, is it more readable now?
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4732 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgBPhvC36f0SCj0rR3:-Llifhnf7Xu2rBJbStsr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4732)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> (int rowIndex
> ```
After reading this method further, I would have preferred `targetRowIndex` to make it foolproof easy to read the logic checks
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4734 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk--bU02Y-Z1OWrsg3X:-Lli9lED2CBCZK2bEpxf:b94j2um) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4734)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I agree. We have existing methods `scrollToRow` (in two places), `scrollToSpacer` (in two places), and `scrollToRowAndSpacer`, and all of them need _almost_ the same rather complex logic so they are all calling this method now instead of using three different scrolling logics that didn't even match. Those two variables are there to indicate which of t [...]

2019-08-08 08:52 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 79 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2834 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk-92zTBI3eSvyDNPBS:-LlkQEZA4vZATuFduwEq:bcc75ke) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2834)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I've been using re-purpose all over, I can change it if you want but that's going to need a bigger edit pass. See another answer further down about discussing possible new ways to call the same thing.

The comment is there because I kept forgetting what `moveAndUpdateEscalatorRows` did, exactly, in the early days of working on these changes. It's clear that it moves and updates rows, but it's difficult to see with a glance what exactly is moved and where and why if you don't already know how the logic works.
</blockquote></details>

Bigger edit cycle for `re-purpose` -> `recycle` done.


<!-- Sent from Reviewable.io -->

2019-08-08 10:48 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 1 of 17 files reviewed, 79 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4754 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg9mPR-CoidFxmlwAW:-LlkpPYi5kPAP-SHaxTO:b-4h7nmk) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4754)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I wrote it that way because I thought `Math.ceil` rounds the wrong way if the contents are negative and I personally find it less confusing to round using positive numbers rather than switch to `Math.floor` for negative numbers. Could switch to using `Math.abs(padding)` and then multiply with -1 if `padding` is negative, I suppose, but now I need to re-think how the rounding should actually happen if the padding is negative. The whole concept kind of breaks my brain, because it's possible to call scrollToRow and end up with that row not even being within the visual range when you use negative paddings. Can't imagine it being a very common use case, but since we have that feature it needs to work. I know I spent quite a while puzzling things out when I was writing this, but I can't remember anymore what my conclusions were exactly, so now I need to figure it out again.
</blockquote></details>

Now I'm thinking I got it wrong the first time around so I removed the different handling.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4889 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgMSGl1gFBUMXuOZ7-:-LlkpfL6E54kGrbi9mk4:bs4dg43) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4889)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

The parent method is indeed very close to row limit, but mostly I'm falling asleep so I'll have to return to that potential dividing question later. Removed the unnecessary return in the meanwhile.
</blockquote></details>

Separated into two different methods.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4935 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgODYN154lI8heZhy0:-Llkpoqs9BMXgzpcNOYm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4935)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> rowIndex
> ```
`targetRowIndex` ? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-15 13:03 UTC, pleku requested changes
> Reviewed 2 of 6 files at r15, 3 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 6 of 17 files reviewed, 69 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 588 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljz_Yci4KdB22rXcrzj:-LmKKPhD3J8jYHJhq2Ee:b-5njq42) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L588)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Went with just `updatedVisibleRowRange` since it's already in past tense, but I can add the `previous` if you feel strongly about it.
</blockquote></details>

Now after the renaming and reading all the occurrences for the member field, I would use the name `latestVisibleRowRange` instead of `updatedVisibleRowRange`, but up to you if you agree
___
*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 97 at r16](https://reviewable.io/reviews/vaadin/framework/11438#-LmKLI1YDv43UlgJKUIV:-LmKLI1YDv43UlgJKUIW:b-jldenv) ([raw file](https://github.com/vaadin/framework/blob/b8a81c317d476f953435a08ddffc769d27be94b4/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L97)):*
> ```Java
>      * the same round trip has had a chance to happen, so there needs to be a
>      * delay.
>      *
> ```

Please add the comment about using intentionally using `scheduleFinally` in all methods to avoid flickering
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3865 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljzm4HK1Gt6uoF0AiSc:-LmKMaALEuUpiAujO1p4:b85phja) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3865)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

The mode isn't changed, it just checks whether the mode is undefined. The undefined height handling was added long after the fact so it's a bit glued on, basically every time something changes it simply sets the height to whatever the new total row amount is (rendered spacers are obviously taken into account).
</blockquote></details>

I don't know what to add so maybe I'll just cry inside a little
___
*[shared/src/main/java/com/vaadin/shared/ui/grid/DetailsManagerState.java, line 25 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzJ2KtC8ccFFX9cpEA:-LmKLijS85n66qWMFOwW:b-i6m8mc) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/shared/src/main/java/com/vaadin/shared/ui/grid/DetailsManagerState.java#L25)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Because every Grid has a DetailsManager even if they don't have a DetailsGenerator, and something needs to tell DetailsManagerConnector when it doesn't need to do any checking because having any details simply isn't an option.
</blockquote></details>

Ok. Seems like an overall design flaw but not necessary to address in this PR 


<!-- Sent from Reviewable.io -->

2019-08-15 15:21 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 4 of 17 files reviewed, 68 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 588 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Ljz_Yci4KdB22rXcrzj:-LmKraZXDlp2Lkpd9UAW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L588)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Now after the renaming and reading all the occurrences for the member field, I would use the name `latestVisibleRowRange` instead of `updatedVisibleRowRange`, but up to you if you agree
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 97 at r16](https://reviewable.io/reviews/vaadin/framework/11438#-LmKLI1YDv43UlgJKUIV:-LmKrfq41Z5cdd6M9MHL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b8a81c317d476f953435a08ddffc769d27be94b4/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L97)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add the comment about using intentionally using `scheduleFinally` in all methods to avoid flickering
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-20 10:18 UTC, pleku requested changes
> Reviewed 1 of 4 files at r16, 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 7 of 17 files reviewed, 20 unresolved discussions (waiting on @Ansku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2115 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzujF94A4MpbvdN3vD:-LmOH-YxD57UCqEhVFHk:bm7x9ts) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2115)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

That's not actually about hidden spacers, it's for attaching the Grid itself with `display: none` and then turning it visible again. If the calculations are done when the Grid is still hidden some of the defaults will be determined wrong and never checked again. When we skip the calculations entirely while there is nothing to calculate the check will be performed by default when the visibility changes, at which point the defaults get correct values, and we can avoid forcing the calculations just in case when they are not actually needed.
</blockquote></details>

Crazy stuff. So this bit of escalator internal row container implementation details is dependent on how grid might be hidden ...
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2866 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk34FJe5A4CX52AdFIT:-LmONT5B4rNiw9CU63y-:bf5whi) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2866)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Yes, `getRowHeightsSumBetweenPx` removes spacer heights from the total height sum. That's an existing method so I didn't rename it, but it _is_ private so renaming is an option. Would `getRowHeightsSumBetweenPxExcludingSpacers` make it more readable?
</blockquote></details>

Rename could be Ok, minimum is a comment in the call above clarifying that `getRowHeightsSumBetweenPx` doesn't contain spacers. It is now confusing as the comment says "so the spacers have to be taken into account"
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2878 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk3Eh351QWI1qoQrDpG:-LmOO8rQ4rjDhdDPzkvJ:bkzzb9l) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2878)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

They aren't always moved from top to the bottom or from bottom to the top, sometimes they are moved to or from the middle and it's even possible to move them from middle to another point in the middle. Neither 'move' nor 'transfer' cover the 'and update' part of what is happening and gets too easily confused with simple re-positioning that also happens a lot within this handling. And 'move and update' didn't feel very handy when I was writing these comments to myself trying to figure out what was going on. Probably could have gone with 'reuse' or that 'recycle' that you suggested above, but either didn't think of those at the time or I was working somewhere where that word was already used for something else. Or just happened to prefer re-purpose as a description at the time. Can't remember for sure, the first iterations are from November. By now my brain is pretty thoroughly wired to use re-purpose, but it can certainly be switched to something else if needed. Preferences?
</blockquote></details>

recycle ftw 
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4102 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg2-WA9E-OxI4UFlmx:-LmPT5mA9Xpk6crToV_U:b-5cm33v) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4102)):*
> ```
>             // remove extra dom rows and their spacers if any
>             double removedFromDomSpacerHeights = 0d;
>             if (rowsToRemoveFromDom > 0) {
> ```
This is from above in this method, from where the code execution will run into this method, so you point is either not correct or confusing me, so please do elaborate.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4382 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9Nek7A4u7rf5YVqoR:-LmcMs_e0X1fPdYqzC9R:bp1l3ji) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4382)):*
> ```
>                 int removeFromAbove = Math.max(0,
>                         Math.min(-rowDiff, oldFirstVisibleVisualIndex));
> ```

Ok. But now the ^ variable sounds like it would be similar as `spacersRemovedFromAbove`, so maybe that should be renamed instead to avoid confusion.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4623 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9PEQD0nynLMhlvPnS:-LmcPSJ4-u3J0axI6lE-:blv5b5m) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4623)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Because sometimes the method is called with a spacer element and doesn't recognize it without this handling. It causes issues with focused element handling in scrolling. It wasn't needed previously because you couldn't scroll away from the focus and then back again since the spacer was there forever, but now that spacers are also temporary elements it needs a similar handling than scrolling out of a focused row and back does.
</blockquote></details>

Please answer this one also in code, not just in review comments
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4725 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzzzxN9HOA9soaELA0:-LmhZb7u1amVCLmnvtgL:bigfj4m) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4725)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I was wondering if I should just remove this altogether, as it's not public or protected (although it _is_ package protected) and it's never used internally anymore?
</blockquote></details>

Could check the reason for introducing it from git history/blame and then decide if it was opened for add-on reasons. If not, should be safe to remove
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4734 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk--bU02Y-Z1OWrsg3X:-Lmh_Lgq4KQzpXK-WKkl:bk4gvxe) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4734)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

How about switching to use an Enum, e.g. `ScrollType.ROW`, `ScrollType.SPACER`, `ScrollType.ROW_AND_SPACER` or something?
</blockquote></details>

Would be to a lot easier to grasp and in the hypothetical case that there would be more targets than rows and spacers, it would be easy to add without breaking change
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4755 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgAfNj-bjMSAi_04re:-LmhchDu1n65TEkg53Hz:b-kepkup) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4755)):*
<details><summary><i>Pre [...]

2019-08-20 11:33 UTC, pleku requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 7 of 17 files reviewed, 20 unresolved discussions (waiting on @Ansku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5197 at r17](https://reviewable.io/reviews/vaadin/framework/11438#-LmimeXO-ic38D_ezDnG:-LmimeXP2OC0KrZUNK7E:b-3t1cae) ([raw file](https://github.com/vaadin/framework/blob/1e8ff3664d4b6bd51df5ffc1cae919816bb54200/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5197)):*
> ```
>         private double calculateScrollPositionForScrollToRowSpacerOrBoth(
>                 int targetRowIndex, ScrollDestination destination,
>                 double padding, boolean scrollToSpacer, boolean scrollToBoth) {
> ```
I don't understand the role of this method as it seems to me that the calling method `scrollToROwSpacerOrBoth` handles (or tries currently) to figure out the row to use as the target based on the scrolling direction and padding (which has issues).

I think I need to re-review this again once the calling method things have been addressed, it seems very weird that this method is also looking at the padding, but this time as pixels ...


<!-- Sent from Reviewable.io -->

2019-08-20 21:23 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 6 of 17 files reviewed, 20 unresolved discussions (waiting on @Ansku and @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2866 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk34FJe5A4CX52AdFIT:-LmkT9xd0mnbIFN90PW7:bt1b19p) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2866)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Rename could be Ok, minimum is a comment in the call above clarifying that `getRowHeightsSumBetweenPx` doesn't contain spacers. It is now confusing as the comment says "so the spacers have to be taken into account"
</blockquote></details>

Renamed.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4102 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Llg2-WA9E-OxI4UFlmx:-LmirlQM4JEa6acL8ETJ:bnoe16i) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4102)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>             // remove extra dom rows and their spacers if any
>             double removedFromDomSpacerHeights = 0d;
>             if (rowsToRemoveFromDom > 0) {
> ```
This is from above in this method, from where the code execution will run into this method, so you point is either not correct or confusing me, so please do elaborate.
</blockquote></details>

In that use case rows are recycled. It's not possible to have `rowsToIncludeFromAbove <= 0`, `rowsToIncludeFromBelow <= 0`, and `rowsToRemoveFromDom > 0` all true simultaneously at this point, because otherwise all rows have been removed from either above or below the visual range and this method never would have been called. If rows are removed from within visual range, something has to be removed or recycled, and recycling causes new rows to be added from above or below
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4382 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9Nek7A4u7rf5YVqoR:-LmkWHV_CvQG0AM-bbIX:bt1b19p) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4382)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 int removeFromAbove = Math.max(0,
>                         Math.min(-rowDiff, oldFirstVisibleVisualIndex));
> ```

Ok. But now the ^ variable sounds like it would be similar as `spacersRemovedFromAbove`, so maybe that should be renamed instead to avoid confusion.
</blockquote></details>

Renamed.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4623 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk9PEQD0nynLMhlvPnS:-Lmj-wqF9qXXkQ44b2wG:byk9j6j) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4623)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please answer this one also in code, not just in review comments
</blockquote></details>

Actually, I remembered wrong -- I tested this again and it was switching tabulator focus into a scrolled Escalator that broke without this particular change, not the focus handling when scrolling out and back again. The correct cell element is identified but it gets wrong index when the element to focus is within a spacer, and consequently Escalator's tabulator handling scrolls to that wrong index. The logic is already broken in the same way in the current version, but accidentally stays close enough to the correct row that the regression test (`EscalatorSpacerTest.spacerScrolledIntoView`) doesn't break -- when the tabulator happens, instead of trying to scroll to row 50 where the Escalator already is it scrolls to row 37, which is only two rows up from the first completely visible row, and the spacer on row 50 is big enough that scrolling up two rows doesn't scroll it out of view and cause the focus to be lost. In the new version the logic for how many rows exist and how are arranged in relation to the viewport is a bit different, so the `topRowLogicalIndex` is also different and causes Escalator to attempt to scroll to row 30, which moves the spacer out of visual range and the regression test fails.

In other words, this is what the method always should have done for spacers, they are TableRowElements but you can't check their index with the same logic (`ropRowLogicalIndex` +  visualIndex) because they don't live in the same container (which makes their visualIndex always -1). If you'd prefer I think I can move the fix within `getLogicalRowIndex` instead, but that one is called from a lot more places and for most of those spacers are not a consideration. For now I just copied over JavaDocs from the parent and modified them to mention spacers. 
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4725 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LjzzzxN9HOA9soaELA0:-LmjGnprC6GYV9c4IasM:bk2rokj) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4725)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could check the reason for introducing it from git history/blame and then decide if it was opened for add-on reasons. If not, should be safe to remove
</blockquote></details>

It refers to issue #6543 -- as far as I can tell from the rest of the commit the reason was to give `Escalator.scrollToSpacer` (which is a public method also introduced in that commit) an internal implementation within `BodyRowContainerImpl`. Removed.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4734 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-Lk--bU02Y-Z1OWrsg3X:-LmkXTUJ18ghln0RcXjy:bdygwt7) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4734)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Would be to a lot easier to grasp and in the hypothetical case that there would be more targets than rows and spacers, it would be easy to add without breaking change
</blockquote></details>

Enum added, made it package protected to match this method.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4755 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgAfNj-bjMSAi_04re:-Lmk2traEVjvfAqclXLV:b5a7wtu) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4755)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think you missed my point:

I didn't understand how you would get`paddingInRows` by dividing the height of a one row with the requested amount of padding (in pixels). If one requests 100px of padding and row height is 18px, then `paddingInRows` would be `0.2...`. Ok, so requested padding is c. `0.2`of a row. But because of the `ceil` call, this will be rounded up to `1`. For negative padding (-100px), it would be round up to `0`). This is confusing.
For requested padding of 5px for row height of 25px, the `paddingInRows` would be 5. WAT. For same row height 25px and negative padding -7px, it would be -3. This doesn't make the calculations for `targetIndexMinusPadding` and `targetIndexPlusPadding` down below make any sense to me.

To me in th [...]

2019-08-21 11:22 UTC, ZheSun88 commented
by the way, Anna, remember to add the empty `@since` to the new public APIs. @Ansku

2019-08-22 06:09 UTC, pleku requested changes
> Reviewed 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 7 of 17 files reviewed, 4 unresolved discussions (waiting on @Ansku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4755 at r14](https://reviewable.io/reviews/vaadin/framework/11438#-LlgAfNj-bjMSAi_04re:-LmrqWtlCq6vGFM3n83B:b-xng5xh) ([raw file](https://github.com/vaadin/framework/blob/3426bec13b60ddafd6da6e7e4a217677df0d1123/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4755)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Yep, definitely blind to my own code there, and apparently we don't have a regression test that covers that big paddings. Switched the division the other way around, as it should have been.
</blockquote></details>

That is why we have code reviews to help, nobody is expected to make bug free code
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5004 at r17](https://reviewable.io/reviews/vaadin/framework/11438#-LmiVVCc0iKOlzaHx1kf:-LmruPhwCTvuwViVvieC:bsw3z60) ([raw file](https://github.com/vaadin/framework/blob/1e8ff3664d4b6bd51df5ffc1cae919816bb54200/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5004)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

The generic nature of this method makes it horrible to read. We need both numbers in different points of calculations, regardless of whether the padding is positive or negative, because sometimes the padding needs to be calculated below and sometimes above -- and negative padding might switch those around (below is above and above is below), which is why I didn't name them paddingIndexAbove and paddingIndexBelow. I can still switch to that if you think it's clearer, most of the time it will be positive or zero anyway
</blockquote></details>

Then there should probably be a comment here saying that _negative padding will reverse the effect and needs to be taken into account_ so that the IMO bad design of allowing negative padding does not seem as much as a bug or code smell
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4617 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrpKBd7x16rCDUJhxN:-LmrpKBd7x16rCDUJhxO:b1fj3bo) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4617)):*
> ```
> -rowDiff
> ```
Please use `Math.abs` instead
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4637 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrpO9SAMf94jvMGZAC:-LmrpO9SAMf94jvMGZAD:b1fj3bo) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4637)):*
> ```
> -rowDiff
> ```
Please use `Math.abs` instead
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5011 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrrLzk07B99d_wNQBi:-LmrrLzk07B99d_wNQBj:bbq4k9y) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5011)):*
> ```
>                 paddingInRows = (int) Math
>                         .ceil(Double.valueOf(padding) / getDefaultRowHeight());
> ```
If the `padding` can be negative, then this calculation won't work as `Math.ceil` will reduce the result by one (e.g. -1 when it should be -2). 

Also when the result can be a negative number, the calculations afterwards don't really make any sense to me:

>```
>             int targetIndexMinusPadding = targetRowIndex - paddingInRows;
>             int targetIndexPlusPadding = targetRowIndex + paddingInRows;
>```


<!-- Sent from Reviewable.io -->

2019-08-22 08:56 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 4 of 17 files reviewed, 4 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5004 at r17](https://reviewable.io/reviews/vaadin/framework/11438#-LmiVVCc0iKOlzaHx1kf:-LmsTd181INUwFI-h_Ug:b-vdhe0m) ([raw file](https://github.com/vaadin/framework/blob/1e8ff3664d4b6bd51df5ffc1cae919816bb54200/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5004)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Then there should probably be a comment here saying that _negative padding will reverse the effect and needs to be taken into account_ so that the IMO bad design of allowing negative padding does not seem as much as a bug or code smell
</blockquote></details>

Renamed and added a comment based on the reasoning I laid out in the discussion above. Had to extract another bit of code outside of this method as a result, as the method length grew above 150 rows.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4617 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrpKBd7x16rCDUJhxN:-LmsKZccDB_KaFayNkp6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4617)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> -rowDiff
> ```
Please use `Math.abs` instead
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4637 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrpO9SAMf94jvMGZAC:-LmsK_GM8nm6i6oi42KW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4637)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> -rowDiff
> ```
Please use `Math.abs` instead
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5011 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrrLzk07B99d_wNQBi:-LmsLCgiCOAxqNtEfh9U:b-b564gi) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5011)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 paddingInRows = (int) Math
>                         .ceil(Double.valueOf(padding) / getDefaultRowHeight());
> ```
If the `padding` can be negative, then this calculation won't work as `Math.ceil` will reduce the result by one (e.g. -1 when it should be -2). 

Also when the result can be a negative number, the calculations afterwards don't really make any sense to me:

>```
>             int targetIndexMinusPadding = targetRowIndex - paddingInRows;
>             int targetIndexPlusPadding = targetRowIndex + paddingInRows;
>```

</blockquote></details>

That's why it had different handling for negative and positive to start with, but then I realised that you need to treat the row itself as the first padding row rather than the row above/below it, so it works after all. So for example, if you have positive padding of 10px when your row height is 20px, you need one half visible row above and below the target row, but if you have negative padding of -10px, you just need the row itself to be half visible. If your padding is 30px you need a row and a half visible on both sides, with -30px the target row is completely hidden and the row next to it is half visible. And that's why the following calculation works as well, because what it is really calculating is "what is the smallest visible index if the target row is needed at/near the top of the viewport" and "what is the largest visible index if the target row is needed at/near the bottom of the viewport". Renamed accordingly.


<!-- Sent from Reviewable.io -->

2019-08-22 08:56 UTC, Ansku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 4 of 17 files reviewed, 4 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5004 at r17](https://reviewable.io/reviews/vaadin/framework/11438#-LmiVVCc0iKOlzaHx1kf:-LmsTd181INUwFI-h_Ug:b-vdhe0m) ([raw file](https://github.com/vaadin/framework/blob/1e8ff3664d4b6bd51df5ffc1cae919816bb54200/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5004)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Then there should probably be a comment here saying that _negative padding will reverse the effect and needs to be taken into account_ so that the IMO bad design of allowing negative padding does not seem as much as a bug or code smell
</blockquote></details>

Renamed and added a comment based on the reasoning I laid out in the discussion above. Had to extract another bit of code outside of this method as a result, as the method length grew above 150 rows.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4617 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrpKBd7x16rCDUJhxN:-LmsKZccDB_KaFayNkp6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4617)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> -rowDiff
> ```
Please use `Math.abs` instead
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4637 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrpO9SAMf94jvMGZAC:-LmsK_GM8nm6i6oi42KW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4637)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> -rowDiff
> ```
Please use `Math.abs` instead
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5011 at r18](https://reviewable.io/reviews/vaadin/framework/11438#-LmrrLzk07B99d_wNQBi:-LmsLCgiCOAxqNtEfh9U:b-b564gi) ([raw file](https://github.com/vaadin/framework/blob/c3e99cc3267a06079bd04b32391ce697c53a6a4f/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5011)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                 paddingInRows = (int) Math
>                         .ceil(Double.valueOf(padding) / getDefaultRowHeight());
> ```
If the `padding` can be negative, then this calculation won't work as `Math.ceil` will reduce the result by one (e.g. -1 when it should be -2). 

Also when the result can be a negative number, the calculations afterwards don't really make any sense to me:

>```
>             int targetIndexMinusPadding = targetRowIndex - paddingInRows;
>             int targetIndexPlusPadding = targetRowIndex + paddingInRows;
>```

</blockquote></details>

That's why it had different handling for negative and positive to start with, but then I realised that you need to treat the row itself as the first padding row rather than the row above/below it, so it works after all. So for example, if you have positive padding of 10px when your row height is 20px, you need one half visible row above and below the target row, but if you have negative padding of -10px, you just need the row itself to be half visible. If your padding is 30px you need a row and a half visible on both sides, with -30px the target row is completely hidden and the row next to it is half visible. And that's why the following calculation works as well, because what it is really calculating is "what is the smallest visible index if the target row is needed at/near the top of the viewport" and "what is the largest visible index if the target row is needed at/near the bottom of the viewport". Renamed accordingly.


<!-- Sent from Reviewable.io -->

2019-08-27 11:19 UTC, pleku requested changes
> Reviewed 3 of 3 files at r19.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 7 of 17 files reviewed, 1 unresolved discussion (waiting on @Ansku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11438#-LnHnE3X2c8ue0eoyew_:-LnHnE3YDNstpRre9oqD:b-qa1e3i) (no related file):*
Blocked for manual testing on mobile browsers:
- [ ] Chrome Android
- [ ] iOS Safari

---


<!-- Sent from Reviewable.io -->

2019-08-28 06:49 UTC, ZheSun88 reviewed
> Reviewed 1 of 10 files at r1, 1 of 1 files at r4, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 10 of 17 files reviewed, 1 unresolved discussion (waiting on @Ansku)



<!-- Sent from Reviewable.io -->

2019-08-28 07:25 UTC, ZheSun88 reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 11 of 17 files reviewed, 1 unresolved discussion (waiting on @Ansku)



<!-- Sent from Reviewable.io -->

2019-08-28 10:32 UTC, ZheSun88 commented
As the review is still going on.  so far I am quite fine with the test code.

But I just observe one strange behavior with using the UI, `TreeGridDetailsManager`. 

in the GIF, I simulated the test steps, `show all details` and `expend all`. Then after I have clicked the `Leaf 0/0`, the strange thing happened. it looks there is blinking and detail row has been open and closed. 

pay attention on the second click. 
![TreeGridDetailsManager](https://user-images.githubusercontent.com/31067185/63848065-cdb5d000-c997-11e9-81b6-0e7c82613cbe.gif)

is this related to this Patch? or not?

2019-08-28 10:55 UTC, ZheSun88 reviewed
> Reviewed 1 of 1 files at r10, 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @Ansku)



<!-- Sent from Reviewable.io -->

2019-08-28 11:00 UTC, ZheSun88 reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @Ansku)



<!-- Sent from Reviewable.io -->

2019-08-28 12:48 UTC, Ansku reviewed
No, can be reproduced in current master too.

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438#-:-LnNFltT6efX4acD2yFX:b-gey8ok)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @Ansku)



<!-- Sent from Reviewable.io -->

2019-08-28 12:50 UTC, ZheSun88 commented
do we have a ticket for this? Can you create one?

2019-08-28 14:38 UTC, Ansku reviewed
https://github.com/vaadin/framework/issues/11700

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438#-:-LnNeNyuAot1ju893JEP:bgoobyi)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @Ansku)



<!-- Sent from Reviewable.io -->

2019-08-29 06:54 UTC, ZheSun88 approved these changes
> Reviewed 1 of 10 files at r1, 1 of 4 files at r11, 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: all files reviewed, 1 unresolved discussion (waiting on @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11438#-LnHnE3X2c8ue0eoyew_:-LnR89WJDGcWm9PWnXuD:b-u8g3k4) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Blocked for manual testing on mobile browsers:
- [ ] Chrome Android
- [ ] iOS Safari
</blockquote></details>

All tests look fine to me <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> and manually tested some cases with the test UI.  one new issue has been created #11700 

re-ran IE tests, the results look good, no new failures. 

IOS Safari has been tested. currently no surprises, good to go. 

next, to be tested. chrome Android. 

---


<!-- Sent from Reviewable.io -->

2019-08-29 10:33 UTC, ZheSun88 approved these changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438)* status: all files reviewed, 1 unresolved discussion (waiting on @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11438#-LnHnE3X2c8ue0eoyew_:-LnRvwZy6usF8cQhPrkO:b-c34lr7) (no related file):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

All tests look fine to me :lgtm: and manually tested some cases with the test UI.  one new issue has been created #11700 

re-ran IE tests, the results look good, no new failures. 

IOS Safari has been tested. currently no surprises, good to go. 

next, to be tested. chrome Android. 
</blockquote></details>

tested with chrome Android. everything works as expected.  the patch is good to go.

---


<!-- Sent from Reviewable.io -->

2019-08-29 12:49 UTC, pleku approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> fingers crossed 

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11438#-:-LnSQ5_C-Toh9KygU0ri:b-myc6ka)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-29 13:06 UTC, merged