Remove redundant check for for Firefox
vaadin/framework pull request #11471
Opened 2019-02-27 12:04 UTC by anasmi

It seems that in older versions of Firefox (at least, older than 45) the **KeyPress** event should be used instead of **KeyDown** under certain circumstances, for example, if we want to navigate via arrows in table element. At some point (works already on 58 version, the current one is 65) the issue was resolved and starting from Firefox 65 this hook prevents from navigating in the pop-up via keyboard.
Simply removing additional logic makes navigating in both _DateField_ and _InlineDateField_ possible

Fixes #11465

2019-02-28 14:32 UTC, ZheSun88 requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11471)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @anasmi)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11471#-LZoUN95ABZUq4VWnxcd:-LZoUN96AhHUTYj-lEAB:bq6yjh4) (no related file):*
we will need to run the integration test on FF to verify this fix. 
result will be here https://bender.vaadin.com/viewQueued.html?itemId=45009&tab=queuedBuildOverviewTab

---
___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 222 at r2](https://reviewable.io/reviews/vaadin/framework/11471#-LZoV2UZExkb6syEIOpK:-LZoV2UZExkb6syEIOpL:bkz63yk) ([raw file](https://github.com/vaadin/framework/blob/6cc773fb7c717328fbce7255fa419581b7609a92/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L222)):*
> ```
>  if (BrowserInfo.get().isGecko()) {
> ```

so are we sure that there are no users using this anymore?
or should the fix in a way like 

`BrowserInfo.get().getGeckoVersion() > some version`

I am not familiar with this, so I trust you. 


<!-- Sent from Reviewable.io -->

2019-03-01 05:17 UTC, anasmi commented
This code was introduced in 2009-2011 and now I haven't found any reference to what " Firefox auto-repeat" means.  I've tested manually on 58 and 48(I think it's the FF version, when 8.0 was out first) versions and test run with this fix okay on Firefox 45.  I was thinking about version check, but as all supported versions work okay without it, I just remove the whole redundant block. Through, if you think version check is safer - I can do it :)

2019-03-01 07:07 UTC, ZheSun88 reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11471)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @anasmi)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11471#-LZoUN95ABZUq4VWnxcd:-LZs3tR2EDeUg6B1RZYk:b5950mn) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

we will need to run the integration test on FF to verify this fix. 
result will be here https://bender.vaadin.com/viewQueued.html?itemId=45009&tab=queuedBuildOverviewTab
</blockquote></details>

validation looks okay for this PR

---


<!-- Sent from Reviewable.io -->

2019-03-01 07:07 UTC, ZheSun88 reviewed
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11471)* status: all files reviewed, 1 unresolved discussion (waiting on @anasmi)



<!-- Sent from Reviewable.io -->

2019-03-05 12:04 UTC, anasmi commented
@ZheSun88 is there anything I could comment or do further? I've checked that it also works with this fix on MacOs Firefox and pressing any key multiple times doesn't break behavior and navigation happens multiply times

2019-03-06 06:15 UTC, ZheSun88 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11471#-:-L_Gd7TO9sEdDTWWXO2e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-03-06 06:16 UTC, merged