Improving  of caching for hierarchical data to be optional
vaadin/framework pull request #11501
Opened 2019-03-19 10:57 UTC by Klaudeta

Tracking invalidated rows inside `AbstractRemoteDataSource.insertRowData(int firstRowIndex, int count)` and filling cache with these invalidated rows inside `AbstractRemoteDataSource.setRowData(int firstRowIndex, List<T> rowData)` is an enhancement done for hierarchical data inside Vaadin 8. But as AbstractRemoteDataSource is being used also by v7 compatibility package, these changes are causing a regression on V7 compatibility package grid which is reported in here [framework#11477](https://github.com/vaadin/framework/issues/11477).

In order to revert the regression, this PR makes it possible to configure the tracking and filling of cache with invalidated rows as optional, so it is possible for the compatibility package to disable it and have the issue resolved.

Fixes [framework#11477](https://github.com/vaadin/framework/issues/11477)

2019-03-19 10:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/framework?pullRequest=11501) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/framework?pullRequest=11501) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/framework?pullRequest=11501) it.</sub>

2019-03-20 10:45 UTC, pleku requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11501)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Klaudeta and @pleku)

___
*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 749 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPE_md9Em8lY8O48QQ:-LaPE_md9Em8lY8O48QR:b-ozsa5w) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L749)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>             /*
>              * We need to invalidate the cache from the inserted row onwards,
>              * since the cache wants to be a contiguous range. It doesn't
>              * support holes.
>              *
>              * If holes were supported, we could shift the higher part of
>              * "cached" and leave a hole the size of "count" in the middle.
>              */
> ```
</details>

I'm a bit suspicious that this comment could be updated (or should have already), mentioning the situation that invalidated rows are optionally tracked to be optionally used again to get performance gains.
___
*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 766 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPCi-DCuu-pmRo2uHC:-LaPCi-DCuu-pmRo2uHD:b-bq4tfp) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L766)):*
> ```
>                     // Store all invalidated items to a map. Indices are updated
>                     // to
>                     // match what they should be after the insertion.
> ```
Broken comment (not blocking)
___
*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 773 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPGGp79r5zuhN47wLr:-LaPGGp79r5zuhN47wLs:b1t5jcz) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L773)):*
> ```
>             } else {
>                 cached = cached.splitAt(firstRowIndex)[0];
>             }
> ```
This code is duplicated from the other clause and it is still the actual cache invalidation, now even less readable than before. The previous lines are the the special case handling for tracking invalidated rows, I think it would keep the code more readable if the code following the `if (trackInvalidatedRows) {` would be moved to its own method with a descriptive name.

I know that this goes partly beyond the subject of this PR, but as you're adding the if-else clause that increases the complexity of this method, it would be nice to clean this up. So maybe refactor like

```
Range[] splitOldCache = cached.splitAt(firstRowIndex);
cached = splitOldCache[0];
Range invalidated = splitOldCache[1]; // this is just for clarity
if (trackInvalidRows) {
     trackInvalidatedRowsFromCache(invalidated);
}
```
___
*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 972 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPIkUHAIRUkCY5_gJ9:-LaPIkUHAIRUkCY5_gJA:b-oyc2dh) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L972)):*
> ```
> boolean track
> ```
Nitting, but why not `trackInvalitatedRows` like convention ?
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/connectors/RpcDataSourceConnector.java, line 73 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPJ0Ei3kgK0SLgU25q:-LaPJ0Ei3kgK0SLgU25r:b-tk94vo) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/compatibility-client/src/main/java/com/vaadin/v7/client/connectors/RpcDataSourceConnector.java#L73)):*
> ```Java
> 
>         protected RpcDataSource() {
>             setTrackInvalidatedRows(false);
> ```

Please add a comment refering to the github issue you're fixing, or saying eg. "see AbstractRemoteDatasource.....trackInvalidatedRows"
Just so if someone sees that this is different than v7 compatibility package and wants to know why


<!-- Sent from Reviewable.io -->

2019-03-20 10:47 UTC, pleku requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11501)* status: all files reviewed, 4 unresolved discussions (waiting on @Klaudeta)

___
*[uitest/src/test/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelectTest.java, line 23 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPhVwm2XmJTFhYDIVc:-LaPhVwm2XmJTFhYDIVd:b-8mdk7h) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/uitest/src/test/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelectTest.java#L23)):*
> ```
> public void test_insertRowAfterSelected_newRowIsSelected() {
> ```
Please add the github issue link here as a comment


<!-- Sent from Reviewable.io -->

2019-03-20 10:48 UTC, pleku reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11501)* status: all files reviewed, 4 unresolved discussions (waiting on @Klaudeta)

___
*[uitest/src/main/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelect.java, line 39 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPhgCU7Ivy2ZVxEm7L:-LaPhgCU7Ivy2ZVxEm7M:b-4ik29g) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/uitest/src/main/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelect.java#L39)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         Button.ClickListener clickListener = e -> {
>             addNewItem();
>             selectOnlyLastItemIfRequested(checkBox);
>             currInsertionIndex++;
>         };
> ```
</details>

I wonder if the same test exists for the 8 grid and whether or not it works ... but not part of this issue :see_no_evil: 


<!-- Sent from Reviewable.io -->

2019-03-20 21:12 UTC, Klaudeta reviewed
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11501)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 749 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPE_md9Em8lY8O48QQ:-LaRwQ8lDJq2QEvG9Ehx:b-3g67xi) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L749)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>             /*
>              * We need to invalidate the cache from the inserted row onwards,
>              * since the cache wants to be a contiguous range. It doesn't
>              * support holes.
>              *
>              * If holes were supported, we could shift the higher part of
>              * "cached" and leave a hole the size of "count" in the middle.
>              */
> ```
I'm a bit suspicious that this comment could be updated (or should have already), mentioning the situation that invalidated rows are optionally tracked to be optionally used again to get performance gains.
</blockquote></details>

This is not really clear to me to how to enhance the comment. I don't quite get even the meaning of what the actual comment is and means.
___
*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 773 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPGGp79r5zuhN47wLr:-LaRvYC12hF_zgUoyM6p:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L773)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>             } else {
>                 cached = cached.splitAt(firstRowIndex)[0];
>             }
> ```
This code is duplicated from the other clause and it is still the actual cache invalidation, now even less readable than before. The previous lines are the the special case handling for tracking invalidated rows, I think it would keep the code more readable if the code following the `if (trackInvalidatedRows) {` would be moved to its own method with a descriptive name.

I know that this goes partly beyond the subject of this PR, but as you're adding the if-else clause that increases the complexity of this method, it would be nice to clean this up. So maybe refactor like

```
Range[] splitOldCache = cached.splitAt(firstRowIndex);
cached = splitOldCache[0];
Range invalidated = splitOldCache[1]; // this is just for clarity
if (trackInvalidRows) {
     trackInvalidatedRowsFromCache(invalidated);
}
```
</blockquote></details>

Done.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/connectors/RpcDataSourceConnector.java, line 73 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPJ0Ei3kgK0SLgU25q:-LaRvidvExzwUXGb_oYX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/compatibility-client/src/main/java/com/vaadin/v7/client/connectors/RpcDataSourceConnector.java#L73)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add a comment refering to the github issue you're fixing, or saying eg. "see AbstractRemoteDatasource.....trackInvalidatedRows"
Just so if someone sees that this is different than v7 compatibility package and wants to know why
</blockquote></details>

Done.
___
*[uitest/src/main/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelect.java, line 39 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPhgCU7Ivy2ZVxEm7L:-LaRvkHO8JhB4oUvouVk:b-af0vgg) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/uitest/src/main/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelect.java#L39)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>         Button.ClickListener clickListener = e -> {
>             addNewItem();
>             selectOnlyLastItemIfRequested(checkBox);
>             currInsertionIndex++;
>         };
> ```
I wonder if the same test exists for the 8 grid and whether or not it works ... but not part of this issue :see_no_evil: 
</blockquote></details>

It is not possible to have exactly the same code as there is no IndexContainer in V8. Anyway I tried to reproduce similar case with a ListDataProvider for V8 and it was working normally even without this fix. But I'm supposing this is something that is not easily comparable as the V8 DataSource/DataProvider implementation is quite different from V7.
___
*[uitest/src/test/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelectTest.java, line 23 at r2](https://reviewable.io/reviews/vaadin/framework/11501#-LaPhVwm2XmJTFhYDIVc:-LaRwLob4AiCNCfll2uv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6b4d4de4ee4195e4a62fcbf6164520fda584c835/uitest/src/test/java/com/vaadin/v7/tests/components/grid/basicfeatures/server/GridIndexedContainerInsertSelectTest.java#L23)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> public void test_insertRowAfterSelected_newRowIsSelected() {
> ```
Please add the github issue link here as a comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-21 05:55 UTC, pleku approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11501#-:-LaToLqPAbjk2NpkAGiG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-03-21 05:56 UTC, merged