adds release scripts from gate.vaadin.com
vaadin/framework pull request #11928
Opened 2020-03-26 07:05 UTC by paulroemer

2020-03-26 07:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/framework?pullRequest=11928) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/framework?pullRequest=11928) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/framework?pullRequest=11928) it.</sub>

2020-03-26 09:13 UTC, TatuLund approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11928#-:-M3L6YmQB1G5cdQhGrrm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-03-26 09:18 UTC, ZheSun88 requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11928)* status: all files reviewed, 1 unresolved discussion (waiting on @paulroemer)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11928#-M3L7Woo26c4GfmL8DX7:-M3L7Wop93hx3jn_r6-F:brbz1gb) (no related file):*
currently, there is no need to merge this PR. 

all scripts used are in gate.vaadin.com .  

---


<!-- Sent from Reviewable.io -->

2020-03-27 14:31 UTC, ZheSun88 commented
closing this PR now

2020-03-27 14:31 UTC, closed without merging