TreeGrid Sass variables
vaadin/framework pull request #9333
Opened 2017-05-16 13:38 UTC by elmot

Fixes #9311

Resulting screenshots:
![image](https://cloud.githubusercontent.com/assets/5366945/26108658/e051a82a-3a55-11e7-9acf-519b08afc3f8.png)
![image](https://cloud.githubusercontent.com/assets/5366945/26108699/f8cba1c6-3a55-11e7-9bbd-3adf7aa48d0f.png)

2017-05-17 09:00 UTC, jouni requested changes
All the new Sass variables and mixins should be documented with Sassdoc, but I’m not blocking the release because of that. Just make sure you open a new issue for that and put that on the team’s maintenance backlog.

2017-05-17 09:00 UTC, jouni commented on themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss
> +  $indent:2ex !default;
This variable is scoped by the mixin, so I’m not sure the `!default` keyword has any meaning here. It should be moved to the top level and be prefixed with `v-treegrid-`.

Also, why `ex`? That unit is just pretty much never used. `em` would be a safer choice as it is relative to the font size, whereas `ex` is relative to the font family. `1em` is a suitable default value.

Nit: there should be a space between the colon and the value.

2017-05-17 09:00 UTC, jouni commented on themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss
> +    padding-right: 1ex;
Same comment about `ex` as above.

These two lines (width & padding-right) can be combined to just `width: 1em`.

2017-05-17 09:00 UTC, jouni commented on themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss
> +      padding-right: 0.25em;
Why is this padding even needed? Seems totally unnecessary.

2017-05-17 09:00 UTC, jouni commented on themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss
> +        content: $v-treegrid-expander-char-expanded;
These should be extracted to mixins to be consistent with the other parts of Valo. See old Tree theme reference: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree.scss#L246-L263

2017-05-17 09:00 UTC, jouni commented on themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss
>        font-family: FontAwesome;
We should not use Font Awesome any more, should use Vaadin Icons instead.

Correct Vaadin Icons characters are `e7be` (collapsed) and `e7bc` (expanded).

If Vaadin Icons are not always loaded, then we might want to use some icons from the “ThemeIcons” font, which is used by other Valo components. @pleku, WDYT?

2017-05-17 09:00 UTC, jouni commented on themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss
>    $class-depth: depth !default;
Same as for the `$indent`: this is a scoped variable, and I’m not sure you can override that from outside the mixin. So if this is meant to be as an API the developer can override, it should be moved to the top level scope and prefixed with `v-treegrid-`

2017-05-17 09:00 UTC, jouni commented on themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss
>      &::before {
Nit: inconsistent use of colon and double colon for pseudo elements (`:before` vs. `::before`). The latter is the correct syntax (so it’s correct here) and works in all the supported browsers.

For reference: http://www.growingwiththeweb.com/2012/08/pseudo-classes-vs-pseudo-elements.html

2017-05-17 14:12 UTC, elmot commented
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-14:-KkLk5cJvrpMU2Y6JYFk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L14)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

This variable is scoped by the mixin, so I’m not sure the `!default` keyword has any meaning here. It should be moved to the top level and be prefixed with `v-treegrid-`.

Also, why `ex`? That unit is just pretty much never used. `em` would be a safer choice as it is relative to the font size, whereas `ex` is relative to the font family. `1em` is a suitable default value.

Nit: there should be a space between the colon and the value.
</blockquote></details>

Done.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-17:-KkLWLpSYXYrZcmPqE8P:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L17)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Same as for the `$indent`: this is a scoped variable, and I’m not sure you can override that from outside the mixin. So if this is meant to be as an API the developer can override, it should be moved to the top level scope and prefixed with `v-treegrid-`
</blockquote></details>

Done.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-22:-KkLWL_1G6LHFMkgBtLp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L22)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Same comment about `ex` as above.

These two lines (width & padding-right) can be combined to just `width: 1em`.
</blockquote></details>

Done.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-24:-KkLWKlvRfE28d0EjbMm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L24)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Nit: inconsistent use of colon and double colon for pseudo elements (`:before` vs. `::before`). The latter is the correct syntax (so it’s correct here) and works in all the supported browsers.

For reference: http://www.growingwiththeweb.com/2012/08/pseudo-classes-vs-pseudo-elements.html
</blockquote></details>

Done.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-27:-KkLWJ3I_Vo73uY9ToDP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L27)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

We should not use Font Awesome any more, should use Vaadin Icons instead.

Correct Vaadin Icons characters are `e7be` (collapsed) and `e7bc` (expanded).

If Vaadin Icons are not always loaded, then we might want to use some icons from the “ThemeIcons” font, which is used by other Valo components. @pleku, WDYT?
</blockquote></details>

Done.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-33:-KkLWI-Qn4UV3RMqKrHS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L33)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

These should be extracted to mixins to be consistent with the other parts of Valo. See old Tree theme reference: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree.scss#L246-L263
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9333)*
<!-- Sent from Reviewable.io -->

2017-05-17 14:16 UTC, elmot commented
Updated screenshots
![✂-1](https://files.reviewableusercontent.io/images/reviewable/5366945/maW31M7ir_AHHK0kX15ZUAZH.png)
![✂-2](https://files.reviewableusercontent.io/images/reviewable/5366945/8tNmsRD9Yqf_4iSuF5cqcEY8.png)

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-26:-KkLl14DAaLf_yQJILmO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L26)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Why is this padding even needed? Seems totally unnecessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9333#-:-KkLkW8I8TXpEJg4iS8o:b-bxp273)*
<!-- Sent from Reviewable.io -->

2017-05-18 09:51 UTC, jouni commented
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-14:-KkPwkBGG8_v-gTTL0DJ:bw2ou64) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L14)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still using `ex`. Can you explain the reason why that instead of `em` like I proposed?

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-17:-KkPxBCUU3SgOtZRaIGM:bln8kq2) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L17)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should keep the `!default` keyword so the variable can be overridden easily.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 4 at r2](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkPx_67UzEO7N91yHjc:-KkPx_67UzEO7N91yHjd:b-7bixv7) ([raw file](https://github.com/vaadin/framework/blob/d6a327672489d162255517205ab8d51b4b450c6c/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L4)):*
> ```SCSS
> 
> /** Expander width and item indentation constants*/
> $v-treegrid-expander-width:1ex !default;
> ```

Nit: missing space between colon and value.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 6 at r2](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkPxcOUrpEJXD4SmTdK:-KkPxcOUrpEJXD4SmTdL:b-7bixv7) ([raw file](https://github.com/vaadin/framework/blob/d6a327672489d162255517205ab8d51b4b450c6c/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L6)):*
> ```SCSS
> $v-treegrid-expander-width:1ex !default;
> 
> $v-treegrid-indent:2ex !default;
> ```

Nit: missing space between colon and value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9333)*
<!-- Sent from Reviewable.io -->

2017-05-19 07:30 UTC, elmot commented
![✂-1](https://files.reviewableusercontent.io/images/reviewable/5366945/1aHoMFC0KB_IFDxclDcJs48Q.png)

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-14:-KkUVWFWBpXI0l86GaDu:b-f1vfyx) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L14)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Still using `ex`. Can you explain the reason why that instead of `em` like I proposed?
</blockquote></details>

Already fixed.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkGTlLXUm7QppZC9EKj-r1-17:-KkUV27IYzAeMnpeFKRN:b-jsj5f8) ([raw file](https://github.com/vaadin/framework/blob/001fb24d3b21a52a77c0584e4ac1c7809bd59fbb/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L17)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Should keep the `!default` keyword so the variable can be overridden easily.
</blockquote></details>

Ooops. Now it's done.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 4 at r2](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkPx_67UzEO7N91yHjc:-KkURp6voZQJsbrZFI4J:bulpmgl) ([raw file](https://github.com/vaadin/framework/blob/d6a327672489d162255517205ab8d51b4b450c6c/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L4)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Nit: missing space between colon and value.
</blockquote></details>

Already fixed .

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 6 at r2](https://reviewable.io:443/reviews/vaadin/framework/9333#-KkPxcOUrpEJXD4SmTdK:-KkURe6j5hz0foqOQl41:b-f1vfyx) ([raw file](https://github.com/vaadin/framework/blob/d6a327672489d162255517205ab8d51b4b450c6c/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L6)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Nit: missing space between colon and value.
</blockquote></details>

Already fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9333#-:-KkQHXBsdrz8mD7NToWW:bmp7gok)*
<!-- Sent from Reviewable.io -->

2017-05-19 13:23 UTC, jouni commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9333#-:-KkVs8Y5syP5JuUbpbaW:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-05-19 13:24 UTC, hesara commented
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9333)*
<!-- Sent from Reviewable.io -->

2017-05-19 13:25 UTC, merged